{"uid":"b2ec1702e28f7351","name":"TC 03.01.15 Verify Sign in button is clickable","fullName":"tests.test_sign_in.TestRegisteredCustomers#test_03_01_15_sign_in_button_is_clickable","historyId":"68edd443964677e382ff92f5d86bf3c6","time":{"start":1732501549819,"stop":1732501549819,"duration":0},"description":"Check if Sign In button is clickable","descriptionHtml":"<p>Check if Sign In button is clickable</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.466\n  (Session info: chrome=131.0.6778.69)\nStacktrace:\n#0 0x5642375204ca <unknown>\n#1 0x564237033620 <unknown>\n#2 0x56423701b907 <unknown>\n#3 0x56423701b5de <unknown>\n#4 0x564237019616 <unknown>\n#5 0x564237019dff <unknown>\n#6 0x564237029687 <unknown>\n#7 0x5642370404a4 <unknown>\n#8 0x56423704632b <unknown>\n#9 0x56423701a507 <unknown>\n#10 0x564237040304 <unknown>\n#11 0x5642370c515f <unknown>\n#12 0x5642370a6113 <unknown>\n#13 0x564237074be0 <unknown>\n#14 0x564237075bbe <unknown>\n#15 0x5642374ece4b <unknown>\n#16 0x5642374f0de2 <unknown>\n#17 0x5642374d9d2c <unknown>\n#18 0x5642374f1957 <unknown>\n#19 0x5642374bf4bf <unknown>\n#20 0x56423750f348 <unknown>\n#21 0x56423750f510 <unknown>\n#22 0x56423751f346 <unknown>\n#23 0x7fc784a94ac3 <unknown>","statusTrace":"driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"58f188baba4bdb4d815406dc27e37afe\")>\n\n    @pytest.fixture(scope=\"function\")\n    def sign_in_page(driver):\n        sign_in_page = SignInPage(driver, SIGN_IN_URL)\n>       sign_in_page.open()\n\ntests/test_sign_in.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/base_page.py:19: in open\n    self.driver.get(self.url)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7febc1ae0a90>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"timeout\",\"message\":\"timeout: Timed out receiving message from renderer: 2...\\\\n#21 0x56423750f510 \\\\u003Cunknown>\\\\n#22 0x56423751f346 \\\\u003Cunknown>\\\\n#23 0x7fc784a94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.466\nE         (Session info: chrome=131.0.6778.69)\nE       Stacktrace:\nE       #0 0x5642375204ca <unknown>\nE       #1 0x564237033620 <unknown>\nE       #2 0x56423701b907 <unknown>\nE       #3 0x56423701b5de <unknown>\nE       #4 0x564237019616 <unknown>\nE       #5 0x564237019dff <unknown>\nE       #6 0x564237029687 <unknown>\nE       #7 0x5642370404a4 <unknown>\nE       #8 0x56423704632b <unknown>\nE       #9 0x56423701a507 <unknown>\nE       #10 0x564237040304 <unknown>\nE       #11 0x5642370c515f <unknown>\nE       #12 0x5642370a6113 <unknown>\nE       #13 0x564237074be0 <unknown>\nE       #14 0x564237075bbe <unknown>\nE       #15 0x5642374ece4b <unknown>\nE       #16 0x5642374f0de2 <unknown>\nE       #17 0x5642374d9d2c <unknown>\nE       #18 0x5642374f1957 <unknown>\nE       #19 0x5642374bf4bf <unknown>\nE       #20 0x56423750f348 <unknown>\nE       #21 0x56423750f510 <unknown>\nE       #22 0x56423751f346 <unknown>\nE       #23 0x7fc784a94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: TimeoutException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1732499079392,"stop":1732499079459,"duration":67},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder","time":{"start":1732499079459,"stop":1732499079459,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1732501549819,"stop":1732501551087,"duration":1268},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"sign_in_page","time":{"start":1732501551087,"stop":1732501851109,"duration":300022},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.466\n  (Session info: chrome=131.0.6778.69)\nStacktrace:\n#0 0x5642375204ca <unknown>\n#1 0x564237033620 <unknown>\n#2 0x56423701b907 <unknown>\n#3 0x56423701b5de <unknown>\n#4 0x564237019616 <unknown>\n#5 0x564237019dff <unknown>\n#6 0x564237029687 <unknown>\n#7 0x5642370404a4 <unknown>\n#8 0x56423704632b <unknown>\n#9 0x56423701a507 <unknown>\n#10 0x564237040304 <unknown>\n#11 0x5642370c515f <unknown>\n#12 0x5642370a6113 <unknown>\n#13 0x564237074be0 <unknown>\n#14 0x564237075bbe <unknown>\n#15 0x5642374ece4b <unknown>\n#16 0x5642374f0de2 <unknown>\n#17 0x5642374d9d2c <unknown>\n#18 0x5642374f1957 <unknown>\n#19 0x5642374bf4bf <unknown>\n#20 0x56423750f348 <unknown>\n#21 0x56423750f510 <unknown>\n#22 0x56423751f346 <unknown>\n#23 0x7fc784a94ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/tests/test_sign_in.py\", line 17, in sign_in_page\n    sign_in_page.open()\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 19, in open\n    self.driver.get(self.url)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Open a browser","time":{"start":1732501551087,"stop":1732501851109,"duration":300022},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.466\n  (Session info: chrome=131.0.6778.69)\nStacktrace:\n#0 0x5642375204ca <unknown>\n#1 0x564237033620 <unknown>\n#2 0x56423701b907 <unknown>\n#3 0x56423701b5de <unknown>\n#4 0x564237019616 <unknown>\n#5 0x564237019dff <unknown>\n#6 0x564237029687 <unknown>\n#7 0x5642370404a4 <unknown>\n#8 0x56423704632b <unknown>\n#9 0x56423701a507 <unknown>\n#10 0x564237040304 <unknown>\n#11 0x5642370c515f <unknown>\n#12 0x5642370a6113 <unknown>\n#13 0x564237074be0 <unknown>\n#14 0x564237075bbe <unknown>\n#15 0x5642374ece4b <unknown>\n#16 0x5642374f0de2 <unknown>\n#17 0x5642374d9d2c <unknown>\n#18 0x5642374f1957 <unknown>\n#19 0x5642374bf4bf <unknown>\n#20 0x56423750f348 <unknown>\n#21 0x56423750f510 <unknown>\n#22 0x56423751f346 <unknown>\n#23 0x7fc784a94ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 19, in open\n    self.driver.get(self.url)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1732501851136,"stop":1732501851230,"duration":94},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder::0","time":{"start":1732502060397,"stop":1732502060397,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Sign In Page"},{"name":"feature","value":"Registered Customers"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_sign_in"},{"name":"subSuite","value":"TestRegisteredCustomers"},{"name":"host","value":"fv-az523-590"},{"name":"thread","value":"2819-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_sign_in"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"bc1db05efcf06ff0","reportUrl":"https://verafes.github.io/luma_project/504//#testresult/bc1db05efcf06ff0","status":"passed","time":{"start":1732414737727,"stop":1732414737781,"duration":54}}]},"tags":[]},"source":"b2ec1702e28f7351.json","parameterValues":[]}