{"uid":"d982e8a0437a48fa","name":"TC 01_15_01 Verify possibility to vote with 5 stars","fullName":"tests.test_reviews_page.TestReviews#test_tc_01_15_05_check_that_it_is_possible_to_vote_for_5_star","historyId":"755b1737df3094dbd00131c119354342","time":{"start":1718156588769,"stop":1718156593958,"duration":5189},"description":"\n        The user is NOT logged in, located in the product card, section \"Reviews\"\n        1. All required fields are filled with correct data\n        2. Pressed 5 star\n        3.The \"Submit Review\" button is pressed\n        Result: Present in the DOM and visible on the page the message: \"You submitted your review for moderation.\n        This code works when run on Win, Mac, Ubuntu on a real laptop and has the features of working on GitHub Action.\n        When interacting with the GitHub Action, it checks not for the text of the \"Success\" message, but for the \"Success\" URL\"\n        ","descriptionHtml":"<pre><code>    The user is NOT logged in, located in the product card, section &quot;Reviews&quot;\n    1. All required fields are filled with correct data\n    2. Pressed 5 star\n    3.The &quot;Submit Review&quot; button is pressed\n    Result: Present in the DOM and visible on the page the message: &quot;You submitted your review for moderation.\n    This code works when run on Win, Mac, Ubuntu on a real laptop and has the features of working on GitHub Action.\n    When interacting with the GitHub Action, it checks not for the text of the &quot;Success&quot; message, but for the &quot;Success&quot; URL&quot;\n</code></pre>\n","status":"skipped","statusMessage":"XFAIL Flaky behavior on CI\n\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5600d8759e3a <unknown>\n#1 0x5600d844345c <unknown>\n#2 0x5600d848f5b5 <unknown>\n#3 0x5600d848f671 <unknown>\n#4 0x5600d84d3f14 <unknown>\n#5 0x5600d84b24dd <unknown>\n#6 0x5600d84d12cc <unknown>\n#7 0x5600d84b2253 <unknown>\n#8 0x5600d84821c7 <unknown>\n#9 0x5600d8482b3e <unknown>\n#10 0x5600d872027b <unknown>\n#11 0x5600d8724327 <unknown>\n#12 0x5600d870cdae <unknown>\n#13 0x5600d8724df2 <unknown>\n#14 0x5600d86f174f <unknown>\n#15 0x5600d8749128 <unknown>\n#16 0x5600d87492fb <unknown>\n#17 0x5600d8758f6c <unknown>\n#18 0x7f26cbe94ac3 <unknown>","statusTrace":"self = <test_reviews_page.TestReviews object at 0x7f958bef9710>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f620aa14d8bb83bf0fcb66380f57a6e2\")>\n\n    @pytest.mark.xfail(reason=\"Flaky behavior on CI\")\n    @allure.title('TC 01_15_01 Verify possibility to vote with 5 stars')\n    def test_tc_01_15_05_check_that_it_is_possible_to_vote_for_5_star(self, driver):\n        \"\"\"\n        The user is NOT logged in, located in the product card, section \"Reviews\"\n        1. All required fields are filled with correct data\n        2. Pressed 5 star\n        3.The \"Submit Review\" button is pressed\n        Result: Present in the DOM and visible on the page the message: \"You submitted your review for moderation.\n        This code works when run on Win, Mac, Ubuntu on a real laptop and has the features of working on GitHub Action.\n        When interacting with the GitHub Action, it checks not for the text of the \"Success\" message, but for the \"Success\" URL\"\n        \"\"\"\n    \n        \"\"\"Steps\"\"\"\n        page = ReviewsPage(driver, REVIEWS_URL_GENERAL)\n        page.open()\n    \n        \"\"\"Get the current URL and print it\"\"\"\n        page.get_the_current_URL_and_print_it()\n    \n        \"\"\"Steps\"\"\"\n>       page.open_review_menu()\n\ntests/test_reviews_page.py:252: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/reviews_page.py:14: in open_review_menu\n    review_menu = self.element_is_clickable(self.locators.REVIEW_MENU)\npages/base_page.py:80: in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f620aa14d8bb83bf0fcb66380f57a6e2\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f958c169260>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x5600d8759e3a <unknown>\nE       #1 0x5600d844345c <unknown>\nE       #2 0x5600d848f5b5 <unknown>\nE       #3 0x5600d848f671 <unknown>\nE       #4 0x5600d84d3f14 <unknown>\nE       #5 0x5600d84b24dd <unknown>\nE       #6 0x5600d84d12cc <unknown>\nE       #7 0x5600d84b2253 <unknown>\nE       #8 0x5600d84821c7 <unknown>\nE       #9 0x5600d8482b3e <unknown>\nE       #10 0x5600d872027b <unknown>\nE       #11 0x5600d8724327 <unknown>\nE       #12 0x5600d870cdae <unknown>\nE       #13 0x5600d8724df2 <unknown>\nE       #14 0x5600d86f174f <unknown>\nE       #15 0x5600d8749128 <unknown>\nE       #16 0x5600d87492fb <unknown>\nE       #17 0x5600d8758f6c <unknown>\nE       #18 0x7f26cbe94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1718155045618,"stop":1718155045680,"duration":62},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder","time":{"start":1718155045680,"stop":1718155045680,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1718156587497,"stop":1718156588768,"duration":1271},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n        The user is NOT logged in, located in the product card, section \"Reviews\"\n        1. All required fields are filled with correct data\n        2. Pressed 5 star\n        3.The \"Submit Review\" button is pressed\n        Result: Present in the DOM and visible on the page the message: \"You submitted your review for moderation.\n        This code works when run on Win, Mac, Ubuntu on a real laptop and has the features of working on GitHub Action.\n        When interacting with the GitHub Action, it checks not for the text of the \"Success\" message, but for the \"Success\" URL\"\n        ","status":"skipped","statusMessage":"XFAIL Flaky behavior on CI\n\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5600d8759e3a <unknown>\n#1 0x5600d844345c <unknown>\n#2 0x5600d848f5b5 <unknown>\n#3 0x5600d848f671 <unknown>\n#4 0x5600d84d3f14 <unknown>\n#5 0x5600d84b24dd <unknown>\n#6 0x5600d84d12cc <unknown>\n#7 0x5600d84b2253 <unknown>\n#8 0x5600d84821c7 <unknown>\n#9 0x5600d8482b3e <unknown>\n#10 0x5600d872027b <unknown>\n#11 0x5600d8724327 <unknown>\n#12 0x5600d870cdae <unknown>\n#13 0x5600d8724df2 <unknown>\n#14 0x5600d86f174f <unknown>\n#15 0x5600d8749128 <unknown>\n#16 0x5600d87492fb <unknown>\n#17 0x5600d8758f6c <unknown>\n#18 0x7f26cbe94ac3 <unknown>","statusTrace":"self = <test_reviews_page.TestReviews object at 0x7f958bef9710>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f620aa14d8bb83bf0fcb66380f57a6e2\")>\n\n    @pytest.mark.xfail(reason=\"Flaky behavior on CI\")\n    @allure.title('TC 01_15_01 Verify possibility to vote with 5 stars')\n    def test_tc_01_15_05_check_that_it_is_possible_to_vote_for_5_star(self, driver):\n        \"\"\"\n        The user is NOT logged in, located in the product card, section \"Reviews\"\n        1. All required fields are filled with correct data\n        2. Pressed 5 star\n        3.The \"Submit Review\" button is pressed\n        Result: Present in the DOM and visible on the page the message: \"You submitted your review for moderation.\n        This code works when run on Win, Mac, Ubuntu on a real laptop and has the features of working on GitHub Action.\n        When interacting with the GitHub Action, it checks not for the text of the \"Success\" message, but for the \"Success\" URL\"\n        \"\"\"\n    \n        \"\"\"Steps\"\"\"\n        page = ReviewsPage(driver, REVIEWS_URL_GENERAL)\n        page.open()\n    \n        \"\"\"Get the current URL and print it\"\"\"\n        page.get_the_current_URL_and_print_it()\n    \n        \"\"\"Steps\"\"\"\n>       page.open_review_menu()\n\ntests/test_reviews_page.py:252: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/reviews_page.py:14: in open_review_menu\n    review_menu = self.element_is_clickable(self.locators.REVIEW_MENU)\npages/base_page.py:80: in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f620aa14d8bb83bf0fcb66380f57a6e2\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f958c169260>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x5600d8759e3a <unknown>\nE       #1 0x5600d844345c <unknown>\nE       #2 0x5600d848f5b5 <unknown>\nE       #3 0x5600d848f671 <unknown>\nE       #4 0x5600d84d3f14 <unknown>\nE       #5 0x5600d84b24dd <unknown>\nE       #6 0x5600d84d12cc <unknown>\nE       #7 0x5600d84b2253 <unknown>\nE       #8 0x5600d84821c7 <unknown>\nE       #9 0x5600d8482b3e <unknown>\nE       #10 0x5600d872027b <unknown>\nE       #11 0x5600d8724327 <unknown>\nE       #12 0x5600d870cdae <unknown>\nE       #13 0x5600d8724df2 <unknown>\nE       #14 0x5600d86f174f <unknown>\nE       #15 0x5600d8749128 <unknown>\nE       #16 0x5600d87492fb <unknown>\nE       #17 0x5600d8758f6c <unknown>\nE       #18 0x7f26cbe94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException","steps":[{"name":"Open a browser","time":{"start":1718156588769,"stop":1718156588840,"duration":71},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Find clickable elements","time":{"start":1718156588845,"stop":1718156593957,"duration":5112},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5600d8759e3a <unknown>\n#1 0x5600d844345c <unknown>\n#2 0x5600d848f5b5 <unknown>\n#3 0x5600d848f671 <unknown>\n#4 0x5600d84d3f14 <unknown>\n#5 0x5600d84b24dd <unknown>\n#6 0x5600d84d12cc <unknown>\n#7 0x5600d84b2253 <unknown>\n#8 0x5600d84821c7 <unknown>\n#9 0x5600d8482b3e <unknown>\n#10 0x5600d872027b <unknown>\n#11 0x5600d8724327 <unknown>\n#12 0x5600d870cdae <unknown>\n#13 0x5600d8724df2 <unknown>\n#14 0x5600d86f174f <unknown>\n#15 0x5600d8749128 <unknown>\n#16 0x5600d87492fb <unknown>\n#17 0x5600d8758f6c <unknown>\n#18 0x7f26cbe94ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 80, in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', '#tab-label-reviews-title')"},{"name":"timeout","value":"5"}],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"174d0001a0442f49","name":"Screenshot","source":"174d0001a0442f49.png","type":"image/png","size":25664},{"uid":"98d941997c00ac5a","name":"HTML source","source":"98d941997c00ac5a.html","type":"text/html","size":774}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1718156594064,"stop":1718156594127,"duration":63},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder::0","time":{"start":1718157437577,"stop":1718157437577,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Review Page"},{"name":"tag","value":"@pytest.mark.xfail(reason='Flaky behavior on CI')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_reviews_page"},{"name":"subSuite","value":"TestReviews"},{"name":"host","value":"fv-az802-720"},{"name":"thread","value":"2834-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_reviews_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":2,"unknown":0,"total":4},"items":[{"uid":"37935bbaa3699c1f","reportUrl":"https://verafes.github.io/luma_project/338//#testresult/37935bbaa3699c1f","status":"skipped","statusDetails":"XFAIL Flaky behavior on CI\n\nselenium.common.exceptions.TimeoutException: Message:","time":{"start":1718069451639,"stop":1718069458910,"duration":7271}},{"uid":"becaf798541ee3cb","reportUrl":"https://verafes.github.io/luma_project/337//#testresult/becaf798541ee3cb","status":"passed","statusDetails":"XPASS Flaky behavior on CI","time":{"start":1717983172727,"stop":1717983185285,"duration":12558}},{"uid":"a468f42bbdc4ba97","reportUrl":"https://verafes.github.io/luma_project/336//#testresult/a468f42bbdc4ba97","status":"passed","statusDetails":"XPASS Flaky behavior on CI","time":{"start":1717897078213,"stop":1717897090553,"duration":12340}}]},"tags":["@pytest.mark.xfail(reason='Flaky behavior on CI')"]},"source":"d982e8a0437a48fa.json","parameterValues":[]}