{"uid":"f22d9fe47ac910b6","name":"TC 17.01.06 Verify FYP Email field highlighting on click","fullName":"tests.test_forgot_your_password.TestForgotYourPassword#test_17_01_06_email_field_gets_highlighted_when_clicked","historyId":"6446b2fbc472e7d8490633fddd50392a","time":{"start":1730339429323,"stop":1730339429323,"duration":0},"description":"\n        Check the Email field is activated with a cursor and gets highlighted when clicked\n        ","descriptionHtml":"<pre><code>    Check the Email field is activated with a cursor and gets highlighted when clicked\n</code></pre>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.616\n  (Session info: chrome=130.0.6723.58)\nStacktrace:\n#0 0x562b279520aa <unknown>\n#1 0x562b274691a0 <unknown>\n#2 0x562b27451840 <unknown>\n#3 0x562b2745152d <unknown>\n#4 0x562b2744f5bc <unknown>\n#5 0x562b2744fd6f <unknown>\n#6 0x562b2745f1d7 <unknown>\n#7 0x562b274751e4 <unknown>\n#8 0x562b2747a51b <unknown>\n#9 0x562b2745047e <unknown>\n#10 0x562b27474fee <unknown>\n#11 0x562b274f8acb <unknown>\n#12 0x562b274d9b23 <unknown>\n#13 0x562b274a8990 <unknown>\n#14 0x562b274a996e <unknown>\n#15 0x562b2791e16b <unknown>\n#16 0x562b27921f68 <unknown>\n#17 0x562b2790b64c <unknown>\n#18 0x562b27922ae7 <unknown>\n#19 0x562b278f04af <unknown>\n#20 0x562b279404f8 <unknown>\n#21 0x562b279406c0 <unknown>\n#22 0x562b27950f26 <unknown>\n#23 0x7f67ef094ac3 <unknown>","statusTrace":"driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d364601d9fb5e6ed31d68e4162cf2b43\")>\n\n    @pytest.fixture(scope=\"function\")\n    def forgot_psw_page(driver):\n        forgot_psw_page = ForgotYourPasswordPage(driver, FORGOT_YOUR_PASSWORD_URL)\n>       forgot_psw_page.open()\n\ntests/test_forgot_your_password.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/base_page.py:19: in open\n    self.driver.get(self.url)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f44ecead550>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"timeout\",\"message\":\"timeout: Timed out receiving message from renderer: 2...\\\\n#21 0x562b279406c0 \\\\u003Cunknown>\\\\n#22 0x562b27950f26 \\\\u003Cunknown>\\\\n#23 0x7f67ef094ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.616\nE         (Session info: chrome=130.0.6723.58)\nE       Stacktrace:\nE       #0 0x562b279520aa <unknown>\nE       #1 0x562b274691a0 <unknown>\nE       #2 0x562b27451840 <unknown>\nE       #3 0x562b2745152d <unknown>\nE       #4 0x562b2744f5bc <unknown>\nE       #5 0x562b2744fd6f <unknown>\nE       #6 0x562b2745f1d7 <unknown>\nE       #7 0x562b274751e4 <unknown>\nE       #8 0x562b2747a51b <unknown>\nE       #9 0x562b2745047e <unknown>\nE       #10 0x562b27474fee <unknown>\nE       #11 0x562b274f8acb <unknown>\nE       #12 0x562b274d9b23 <unknown>\nE       #13 0x562b274a8990 <unknown>\nE       #14 0x562b274a996e <unknown>\nE       #15 0x562b2791e16b <unknown>\nE       #16 0x562b27921f68 <unknown>\nE       #17 0x562b2790b64c <unknown>\nE       #18 0x562b27922ae7 <unknown>\nE       #19 0x562b278f04af <unknown>\nE       #20 0x562b279404f8 <unknown>\nE       #21 0x562b279406c0 <unknown>\nE       #22 0x562b27950f26 <unknown>\nE       #23 0x7f67ef094ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: TimeoutException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1730338810886,"stop":1730338810950,"duration":64},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder","time":{"start":1730338810950,"stop":1730338810951,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1730339429324,"stop":1730339430518,"duration":1194},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"forgot_psw_page","time":{"start":1730339430518,"stop":1730339730537,"duration":300019},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.616\n  (Session info: chrome=130.0.6723.58)\nStacktrace:\n#0 0x562b279520aa <unknown>\n#1 0x562b274691a0 <unknown>\n#2 0x562b27451840 <unknown>\n#3 0x562b2745152d <unknown>\n#4 0x562b2744f5bc <unknown>\n#5 0x562b2744fd6f <unknown>\n#6 0x562b2745f1d7 <unknown>\n#7 0x562b274751e4 <unknown>\n#8 0x562b2747a51b <unknown>\n#9 0x562b2745047e <unknown>\n#10 0x562b27474fee <unknown>\n#11 0x562b274f8acb <unknown>\n#12 0x562b274d9b23 <unknown>\n#13 0x562b274a8990 <unknown>\n#14 0x562b274a996e <unknown>\n#15 0x562b2791e16b <unknown>\n#16 0x562b27921f68 <unknown>\n#17 0x562b2790b64c <unknown>\n#18 0x562b27922ae7 <unknown>\n#19 0x562b278f04af <unknown>\n#20 0x562b279404f8 <unknown>\n#21 0x562b279406c0 <unknown>\n#22 0x562b27950f26 <unknown>\n#23 0x7f67ef094ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/tests/test_forgot_your_password.py\", line 16, in forgot_psw_page\n    forgot_psw_page.open()\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 19, in open\n    self.driver.get(self.url)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Open a browser","time":{"start":1730339430518,"stop":1730339730537,"duration":300019},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.616\n  (Session info: chrome=130.0.6723.58)\nStacktrace:\n#0 0x562b279520aa <unknown>\n#1 0x562b274691a0 <unknown>\n#2 0x562b27451840 <unknown>\n#3 0x562b2745152d <unknown>\n#4 0x562b2744f5bc <unknown>\n#5 0x562b2744fd6f <unknown>\n#6 0x562b2745f1d7 <unknown>\n#7 0x562b274751e4 <unknown>\n#8 0x562b2747a51b <unknown>\n#9 0x562b2745047e <unknown>\n#10 0x562b27474fee <unknown>\n#11 0x562b274f8acb <unknown>\n#12 0x562b274d9b23 <unknown>\n#13 0x562b274a8990 <unknown>\n#14 0x562b274a996e <unknown>\n#15 0x562b2791e16b <unknown>\n#16 0x562b27921f68 <unknown>\n#17 0x562b2790b64c <unknown>\n#18 0x562b27922ae7 <unknown>\n#19 0x562b278f04af <unknown>\n#20 0x562b279404f8 <unknown>\n#21 0x562b279406c0 <unknown>\n#22 0x562b27950f26 <unknown>\n#23 0x7f67ef094ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 19, in open\n    self.driver.get(self.url)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1730339730561,"stop":1730339730666,"duration":105},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder::0","time":{"start":1730341472995,"stop":1730341472995,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Forgot Your Password Page"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_forgot_your_password"},{"name":"subSuite","value":"TestForgotYourPassword"},{"name":"host","value":"fv-az566-51"},{"name":"thread","value":"3015-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_forgot_your_password"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":3,"unknown":0,"total":4},"items":[{"uid":"fd5160df9d96b43","reportUrl":"https://verafes.github.io/luma_project/479//#testresult/fd5160df9d96b43","status":"passed","time":{"start":1730252642686,"stop":1730252643391,"duration":705}},{"uid":"e0d6f7e0e6e70a","reportUrl":"https://verafes.github.io/luma_project/478//#testresult/e0d6f7e0e6e70a","status":"passed","time":{"start":1730166324803,"stop":1730166325535,"duration":732}},{"uid":"6e0098b2e6fbdd51","reportUrl":"https://verafes.github.io/luma_project/477//#testresult/6e0098b2e6fbdd51","status":"passed","time":{"start":1730080130075,"stop":1730080130733,"duration":658}}]},"tags":[]},"source":"f22d9fe47ac910b6.json","parameterValues":[]}