{"uid":"af50993a8fdfb811","name":"test_check_card_price","fullName":"tests.test_main_page.TestHotSellerSection#test_check_card_price","historyId":"f4026d9f96acc9996f781ecba7818e56","time":{"start":1728092608013,"stop":1728092608826,"duration":813},"description":"This test checks that the card has a price and a price in USD","descriptionHtml":"<p>This test checks that the card has a price and a price in USD</p>\n","status":"skipped","statusMessage":"XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x564e01e0f13a <unknown>\n#1 0x564e01af55e0 <unknown>\n#2 0x564e01afb443 <unknown>\n#3 0x564e01afd105 <unknown>\n#4 0x564e01afd18c <unknown>\n#5 0x564e01b3ef42 <unknown>\n#6 0x564e01b69b22 <unknown>\n#7 0x564e01b39478 <unknown>\n#8 0x564e01b69cee <unknown>\n#9 0x564e01b88d7d <unknown>\n#10 0x564e01b698c3 <unknown>\n#11 0x564e01b376b3 <unknown>\n#12 0x564e01b3868e <unknown>\n#13 0x564e01dd9b3b <unknown>\n#14 0x564e01dddac1 <unknown>\n#15 0x564e01dc6335 <unknown>\n#16 0x564e01dde642 <unknown>\n#17 0x564e01dab49f <unknown>\n#18 0x564e01dfe038 <unknown>\n#19 0x564e01dfe203 <unknown>\n#20 0x564e01e0df8c <unknown>\n#21 0x7efd84694ac3 <unknown>","statusTrace":"self = <test_main_page.TestMainPage.TestHotSellerSection object at 0x7fadb9aa2090>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"55af733fcc7e1d1fe3773a6a1248b518\")>\n\n    @pytest.mark.xfail(reason=\"In CI the test failed in PR#203\")\n    def test_check_card_price(self, driver):\n        \"\"\"This test checks that the card has a price and a price in USD\"\"\"\n        page = MainPage(driver, MAIN_PAGE_URL)\n        page.open()\n>       text = page.check_card_price()\n\ntests/test_main_page.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:49: in check_card_price\n    text = self.get_text(self.locators.CARD_PRICE)\npages/base_page.py:145: in get_text\n    return text.text\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:89: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:394: in _execute\n    return self._parent.execute(command, params)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fadbb5f7990>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#19 0x564e01dfe203 \\\\u003Cunknown>\\\\n#20 0x564e01e0df8c \\\\u003Cunknown>\\\\n#21 0x7efd84694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\nE         (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0x564e01e0f13a <unknown>\nE       #1 0x564e01af55e0 <unknown>\nE       #2 0x564e01afb443 <unknown>\nE       #3 0x564e01afd105 <unknown>\nE       #4 0x564e01afd18c <unknown>\nE       #5 0x564e01b3ef42 <unknown>\nE       #6 0x564e01b69b22 <unknown>\nE       #7 0x564e01b39478 <unknown>\nE       #8 0x564e01b69cee <unknown>\nE       #9 0x564e01b88d7d <unknown>\nE       #10 0x564e01b698c3 <unknown>\nE       #11 0x564e01b376b3 <unknown>\nE       #12 0x564e01b3868e <unknown>\nE       #13 0x564e01dd9b3b <unknown>\nE       #14 0x564e01dddac1 <unknown>\nE       #15 0x564e01dc6335 <unknown>\nE       #16 0x564e01dde642 <unknown>\nE       #17 0x564e01dab49f <unknown>\nE       #18 0x564e01dfe038 <unknown>\nE       #19 0x564e01dfe203 <unknown>\nE       #20 0x564e01e0df8c <unknown>\nE       #21 0x7efd84694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1728092151382,"stop":1728092151446,"duration":64},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder","time":{"start":1728092151447,"stop":1728092151447,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1728092606832,"stop":1728092608012,"duration":1180},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"This test checks that the card has a price and a price in USD","status":"skipped","statusMessage":"XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x564e01e0f13a <unknown>\n#1 0x564e01af55e0 <unknown>\n#2 0x564e01afb443 <unknown>\n#3 0x564e01afd105 <unknown>\n#4 0x564e01afd18c <unknown>\n#5 0x564e01b3ef42 <unknown>\n#6 0x564e01b69b22 <unknown>\n#7 0x564e01b39478 <unknown>\n#8 0x564e01b69cee <unknown>\n#9 0x564e01b88d7d <unknown>\n#10 0x564e01b698c3 <unknown>\n#11 0x564e01b376b3 <unknown>\n#12 0x564e01b3868e <unknown>\n#13 0x564e01dd9b3b <unknown>\n#14 0x564e01dddac1 <unknown>\n#15 0x564e01dc6335 <unknown>\n#16 0x564e01dde642 <unknown>\n#17 0x564e01dab49f <unknown>\n#18 0x564e01dfe038 <unknown>\n#19 0x564e01dfe203 <unknown>\n#20 0x564e01e0df8c <unknown>\n#21 0x7efd84694ac3 <unknown>","statusTrace":"self = <test_main_page.TestMainPage.TestHotSellerSection object at 0x7fadb9aa2090>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"55af733fcc7e1d1fe3773a6a1248b518\")>\n\n    @pytest.mark.xfail(reason=\"In CI the test failed in PR#203\")\n    def test_check_card_price(self, driver):\n        \"\"\"This test checks that the card has a price and a price in USD\"\"\"\n        page = MainPage(driver, MAIN_PAGE_URL)\n        page.open()\n>       text = page.check_card_price()\n\ntests/test_main_page.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:49: in check_card_price\n    text = self.get_text(self.locators.CARD_PRICE)\npages/base_page.py:145: in get_text\n    return text.text\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:89: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:394: in _execute\n    return self._parent.execute(command, params)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fadbb5f7990>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#19 0x564e01dfe203 \\\\u003Cunknown>\\\\n#20 0x564e01e0df8c \\\\u003Cunknown>\\\\n#21 0x7efd84694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\nE         (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0x564e01e0f13a <unknown>\nE       #1 0x564e01af55e0 <unknown>\nE       #2 0x564e01afb443 <unknown>\nE       #3 0x564e01afd105 <unknown>\nE       #4 0x564e01afd18c <unknown>\nE       #5 0x564e01b3ef42 <unknown>\nE       #6 0x564e01b69b22 <unknown>\nE       #7 0x564e01b39478 <unknown>\nE       #8 0x564e01b69cee <unknown>\nE       #9 0x564e01b88d7d <unknown>\nE       #10 0x564e01b698c3 <unknown>\nE       #11 0x564e01b376b3 <unknown>\nE       #12 0x564e01b3868e <unknown>\nE       #13 0x564e01dd9b3b <unknown>\nE       #14 0x564e01dddac1 <unknown>\nE       #15 0x564e01dc6335 <unknown>\nE       #16 0x564e01dde642 <unknown>\nE       #17 0x564e01dab49f <unknown>\nE       #18 0x564e01dfe038 <unknown>\nE       #19 0x564e01dfe203 <unknown>\nE       #20 0x564e01e0df8c <unknown>\nE       #21 0x7efd84694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException","steps":[{"name":"Open a browser","time":{"start":1728092608013,"stop":1728092608697,"duration":684},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Get element text","time":{"start":1728092608697,"stop":1728092608825,"duration":128},"status":"broken","statusMessage":"selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=129.0.6668.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x564e01e0f13a <unknown>\n#1 0x564e01af55e0 <unknown>\n#2 0x564e01afb443 <unknown>\n#3 0x564e01afd105 <unknown>\n#4 0x564e01afd18c <unknown>\n#5 0x564e01b3ef42 <unknown>\n#6 0x564e01b69b22 <unknown>\n#7 0x564e01b39478 <unknown>\n#8 0x564e01b69cee <unknown>\n#9 0x564e01b88d7d <unknown>\n#10 0x564e01b698c3 <unknown>\n#11 0x564e01b376b3 <unknown>\n#12 0x564e01b3868e <unknown>\n#13 0x564e01dd9b3b <unknown>\n#14 0x564e01dddac1 <unknown>\n#15 0x564e01dc6335 <unknown>\n#16 0x564e01dde642 <unknown>\n#17 0x564e01dab49f <unknown>\n#18 0x564e01dfe038 <unknown>\n#19 0x564e01dfe203 <unknown>\n#20 0x564e01e0df8c <unknown>\n#21 0x7efd84694ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 145, in get_text\n    return text.text\n           ^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py\", line 89, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py\", line 394, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Find a visible element","time":{"start":1728092608698,"stop":1728092608776,"duration":78},"status":"passed","steps":[{"name":"Find a present element","time":{"start":1728092608698,"stop":1728092608717,"duration":19},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', \"li[class='product-item']:nth-child(3) span[class='price']\")"},{"name":"timeout","value":"5"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Go to specified element","time":{"start":1728092608717,"stop":1728092608730,"duration":13},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"element","value":"<selenium.webdriver.remote.webelement.WebElement (session=\"55af733fcc7e1d1fe3773a6a1248b518\", element=\"f.18E9553F4358994F60421C7C0168FC6C.d.4B17B2A32EBAF8D51D29A82FAA813A0C.e.9\")>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', \"li[class='product-item']:nth-child(3) span[class='price']\")"},{"name":"timeout","value":"10"}],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', \"li[class='product-item']:nth-child(3) span[class='price']\")"}],"shouldDisplayMessage":true,"stepsCount":3,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"8565eaa2f5195672","name":"Screenshot","source":"8565eaa2f5195672.png","type":"image/png","size":96277},{"uid":"624373ba019aa1ac","name":"HTML source","source":"624373ba019aa1ac.html","type":"text/html","size":109666}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1728092609067,"stop":1728092609137,"duration":70},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder::0","time":{"start":1728093356717,"stop":1728093356717,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Testing Hot Seller Section"},{"name":"epic","value":"Main Page"},{"name":"tag","value":"@pytest.mark.xfail(reason='In CI the test failed in PR#203')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_main_page"},{"name":"subSuite","value":"TestMainPage"},{"name":"host","value":"fv-az692-231"},{"name":"thread","value":"2880-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_main_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":1,"passed":6,"unknown":0,"total":7},"items":[{"uid":"dc374d6ed86ec4a","reportUrl":"https://verafes.github.io/luma_project/453//#testresult/dc374d6ed86ec4a","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1728006348684,"stop":1728006349551,"duration":867}},{"uid":"e9e3fd3ef6d65c31","reportUrl":"https://verafes.github.io/luma_project/452//#testresult/e9e3fd3ef6d65c31","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1727919880894,"stop":1727919882118,"duration":1224}},{"uid":"a800d8d1e2130590","reportUrl":"https://verafes.github.io/luma_project/451//#testresult/a800d8d1e2130590","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1727833498800,"stop":1727833499473,"duration":673}},{"uid":"9dc66041c90565b2","reportUrl":"https://verafes.github.io/luma_project/450//#testresult/9dc66041c90565b2","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1727747635054,"stop":1727747635725,"duration":671}},{"uid":"8e285f1ed8183ad6","reportUrl":"https://verafes.github.io/luma_project/449//#testresult/8e285f1ed8183ad6","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1727660921777,"stop":1727660922470,"duration":693}},{"uid":"da3815aa82acef2d","reportUrl":"https://verafes.github.io/luma_project/448//#testresult/da3815aa82acef2d","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1727574679724,"stop":1727574680601,"duration":877}}]},"tags":["@pytest.mark.xfail(reason='In CI the test failed in PR#203')"]},"source":"af50993a8fdfb811.json","parameterValues":[]}