{"uid":"eed731ea4cb67836","name":"TC 03.02.02 to 03_02_10 Verify Error on Failed Login with invalid credentials","fullName":"tests.test_sign_in.TestFailedLogin#test_03_02_02_to_10_error_if_login_with_invalid_credentials","historyId":"eb8553534ee747a20415e861783cb15a","time":{"start":1730945735121,"stop":1730945735121,"duration":0},"description":"Check error on Failed Login with invalid credentials, case-sensitive password and password with spaces","descriptionHtml":"<p>Check error on Failed Login with invalid credentials, case-sensitive password and password with spaces</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.555\n  (Session info: chrome=130.0.6723.91)\nStacktrace:\n#0 0x56526bf5c13a <unknown>\n#1 0x56526ba77460 <unknown>\n#2 0x56526ba5fb00 <unknown>\n#3 0x56526ba5f7ed <unknown>\n#4 0x56526ba5d87c <unknown>\n#5 0x56526ba5e02f <unknown>\n#6 0x56526ba6d497 <unknown>\n#7 0x56526ba83474 <unknown>\n#8 0x56526ba887ab <unknown>\n#9 0x56526ba5e73e <unknown>\n#10 0x56526ba832d8 <unknown>\n#11 0x56526bb06d5b <unknown>\n#12 0x56526bae7db3 <unknown>\n#13 0x56526bab6c10 <unknown>\n#14 0x56526bab7bee <unknown>\n#15 0x56526bf283cb <unknown>\n#16 0x56526bf2c368 <unknown>\n#17 0x56526bf15eec <unknown>\n#18 0x56526bf2cee7 <unknown>\n#19 0x56526befb13f <unknown>\n#20 0x56526bf4a858 <unknown>\n#21 0x56526bf4aa20 <unknown>\n#22 0x56526bf5afb6 <unknown>\n#23 0x7fb4d5294ac3 <unknown>","statusTrace":"driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f7faaa11ffc3c230435ecbfe9fb65d17\")>\n\n    @pytest.fixture(scope=\"function\")\n    def sign_in_page(driver):\n        sign_in_page = SignInPage(driver, SIGN_IN_URL)\n>       sign_in_page.open()\n\ntests/test_sign_in.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/base_page.py:19: in open\n    self.driver.get(self.url)\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f47d0a36c90>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"timeout\",\"message\":\"timeout: Timed out receiving message from renderer: 2...\\\\n#21 0x56526bf4aa20 \\\\u003Cunknown>\\\\n#22 0x56526bf5afb6 \\\\u003Cunknown>\\\\n#23 0x7fb4d5294ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.555\nE         (Session info: chrome=130.0.6723.91)\nE       Stacktrace:\nE       #0 0x56526bf5c13a <unknown>\nE       #1 0x56526ba77460 <unknown>\nE       #2 0x56526ba5fb00 <unknown>\nE       #3 0x56526ba5f7ed <unknown>\nE       #4 0x56526ba5d87c <unknown>\nE       #5 0x56526ba5e02f <unknown>\nE       #6 0x56526ba6d497 <unknown>\nE       #7 0x56526ba83474 <unknown>\nE       #8 0x56526ba887ab <unknown>\nE       #9 0x56526ba5e73e <unknown>\nE       #10 0x56526ba832d8 <unknown>\nE       #11 0x56526bb06d5b <unknown>\nE       #12 0x56526bae7db3 <unknown>\nE       #13 0x56526bab6c10 <unknown>\nE       #14 0x56526bab7bee <unknown>\nE       #15 0x56526bf283cb <unknown>\nE       #16 0x56526bf2c368 <unknown>\nE       #17 0x56526bf15eec <unknown>\nE       #18 0x56526bf2cee7 <unknown>\nE       #19 0x56526befb13f <unknown>\nE       #20 0x56526bf4a858 <unknown>\nE       #21 0x56526bf4aa20 <unknown>\nE       #22 0x56526bf5afb6 <unknown>\nE       #23 0x7fb4d5294ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1730943375835,"stop":1730943375901,"duration":66},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder","time":{"start":1730943375901,"stop":1730943375901,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1730945735122,"stop":1730945736390,"duration":1268},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"sign_in_page","time":{"start":1730945736391,"stop":1730946036409,"duration":300018},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.555\n  (Session info: chrome=130.0.6723.91)\nStacktrace:\n#0 0x56526bf5c13a <unknown>\n#1 0x56526ba77460 <unknown>\n#2 0x56526ba5fb00 <unknown>\n#3 0x56526ba5f7ed <unknown>\n#4 0x56526ba5d87c <unknown>\n#5 0x56526ba5e02f <unknown>\n#6 0x56526ba6d497 <unknown>\n#7 0x56526ba83474 <unknown>\n#8 0x56526ba887ab <unknown>\n#9 0x56526ba5e73e <unknown>\n#10 0x56526ba832d8 <unknown>\n#11 0x56526bb06d5b <unknown>\n#12 0x56526bae7db3 <unknown>\n#13 0x56526bab6c10 <unknown>\n#14 0x56526bab7bee <unknown>\n#15 0x56526bf283cb <unknown>\n#16 0x56526bf2c368 <unknown>\n#17 0x56526bf15eec <unknown>\n#18 0x56526bf2cee7 <unknown>\n#19 0x56526befb13f <unknown>\n#20 0x56526bf4a858 <unknown>\n#21 0x56526bf4aa20 <unknown>\n#22 0x56526bf5afb6 <unknown>\n#23 0x7fb4d5294ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/tests/test_sign_in.py\", line 17, in sign_in_page\n    sign_in_page.open()\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 19, in open\n    self.driver.get(self.url)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Open a browser","time":{"start":1730945736391,"stop":1730946036409,"duration":300018},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.555\n  (Session info: chrome=130.0.6723.91)\nStacktrace:\n#0 0x56526bf5c13a <unknown>\n#1 0x56526ba77460 <unknown>\n#2 0x56526ba5fb00 <unknown>\n#3 0x56526ba5f7ed <unknown>\n#4 0x56526ba5d87c <unknown>\n#5 0x56526ba5e02f <unknown>\n#6 0x56526ba6d497 <unknown>\n#7 0x56526ba83474 <unknown>\n#8 0x56526ba887ab <unknown>\n#9 0x56526ba5e73e <unknown>\n#10 0x56526ba832d8 <unknown>\n#11 0x56526bb06d5b <unknown>\n#12 0x56526bae7db3 <unknown>\n#13 0x56526bab6c10 <unknown>\n#14 0x56526bab7bee <unknown>\n#15 0x56526bf283cb <unknown>\n#16 0x56526bf2c368 <unknown>\n#17 0x56526bf15eec <unknown>\n#18 0x56526bf2cee7 <unknown>\n#19 0x56526befb13f <unknown>\n#20 0x56526bf4a858 <unknown>\n#21 0x56526bf4aa20 <unknown>\n#22 0x56526bf5afb6 <unknown>\n#23 0x7fb4d5294ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 19, in open\n    self.driver.get(self.url)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1730946036435,"stop":1730946036541,"duration":106},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder::0","time":{"start":1730946108342,"stop":1730946108342,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"Failed Login Functionality"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_sign_in"},{"name":"subSuite","value":"TestFailedLogin"},{"name":"host","value":"fv-az2022-763"},{"name":"thread","value":"2800-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_sign_in"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"email","value":"'teston120@mailinator.com'"},{"name":"password","value":"'test#12p@ssword'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":3,"unknown":0,"total":5},"items":[{"uid":"9e97092720558749","reportUrl":"https://verafes.github.io/luma_project/486//#testresult/9e97092720558749","status":"broken","statusDetails":"selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input name=\"login[password]\" type=\"password\" autocomplete=\"off\" class=\"input-text\" id=\"pass\" title=\"Password\" data-validate=\"{required:true}\" aria-required=\"true\"> is not clickable at point (560, 845). Other element would receive the click: <iframe id=\"aswift_3\" name=\"aswift_3\" browsingtopics=\"true\" style=\"width: 1005px !important; height: 124px !important; display: block; margin: 0px auto;\" sandbox=\"allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation\" width=\"1005\" height=\"124\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" vspace=\"0\" hspace=\"0\" allowtransparency=\"true\" scrolling=\"no\" allow=\"attribution-reporting; run-ad-auction\" src=\"https://googleads.g.doubleclick.net/pagead/html/r20241030/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271801&amp;client=ca-pub-7399332034053978&amp;fa=1&amp;ifi=4&amp;uci=a!4&amp;btvi=2\" data-google-container-id=\"a!4\" tabindex=\"0\" title=\"Advertisement\" aria-label=\"Advertisement\" data-google-query-id=\"COCX8dPPxokDFb7i_QUdGTYVQA\" data-load-complete=\"true\"></iframe>\n  (Session info: chrome=130.0.6723.58)\nStacktrace:\n#0 0x55bc4a6380aa <unknown>\n#1 0x55bc4a14f1a0 <unknown>\n#2 0x55bc4a1a2896 <unknown>\n#3 0x55bc4a1a082d <unknown>\n#4 0x55bc4a19e2d7 <unknown>\n#5 0x55bc4a19d6f1 <unknown>\n#6 0x55bc4a190cf8 <unknown>\n#7 0x55bc4a1bfd82 <unknown>\n#8 0x55bc4a1906d8 <unknown>\n#9 0x55bc4a1bff4e <unknown>\n#10 0x55bc4a1de866 <unknown>\n#11 0x55bc4a1bfb23 <unknown>\n#12 0x55bc4a18e990 <unknown>\n#13 0x55bc4a18f96e <unknown>\n#14 0x55bc4a60416b <unknown>\n#15 0x55bc4a607f68 <unknown>\n#16 0x55bc4a5f164c <unknown>\n#17 0x55bc4a608ae7 <unknown>\n#18 0x55bc4a5d64af <unknown>\n#19 0x55bc4a6264f8 <unknown>\n#20 0x55bc4a6266c0 <unknown>\n#21 0x55bc4a636f26 <unknown>\n#22 0x7f76ca694ac3 <unknown>","time":{"start":1730858843724,"stop":1730858845237,"duration":1513}},{"uid":"e3a5f682a4b3e311","reportUrl":"https://verafes.github.io/luma_project/485//#testresult/e3a5f682a4b3e311","status":"passed","time":{"start":1730772143824,"stop":1730772146250,"duration":2426}},{"uid":"96ba986bc4ce9d07","reportUrl":"https://verafes.github.io/luma_project/484//#testresult/96ba986bc4ce9d07","status":"passed","time":{"start":1730686019035,"stop":1730686021918,"duration":2883}},{"uid":"dc38d6d229c82117","reportUrl":"https://verafes.github.io/luma_project/483//#testresult/dc38d6d229c82117","status":"passed","time":{"start":1730599662567,"stop":1730599664926,"duration":2359}}]},"tags":[]},"source":"eed731ea4cb67836.json","parameterValues":["'teston120@mailinator.com'","'test#12p@ssword'"]}