{"uid":"b13b95366244d1ad","name":"test_check_card_price","fullName":"tests.test_main_page.TestHotSellerSection#test_check_card_price","historyId":"f4026d9f96acc9996f781ecba7818e56","time":{"start":1699669506232,"stop":1699669507598,"duration":1366},"description":"This test checks that the card has a price and a price in USD","descriptionHtml":"<p>This test checks that the card has a price and a price in USD</p>\n","status":"skipped","statusMessage":"XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x5631d683bfb3 <unknown>\n#1 0x5631d650f4a7 <unknown>\n#2 0x5631d6514509 <unknown>\n#3 0x5631d6516120 <unknown>\n#4 0x5631d65161dc <unknown>\n#5 0x5631d6551782 <unknown>\n#6 0x5631d6578942 <unknown>\n#7 0x5631d654c776 <unknown>\n#8 0x5631d6578b0e <unknown>\n#9 0x5631d6591c02 <unknown>\n#10 0x5631d6578713 <unknown>\n#11 0x5631d654b18b <unknown>\n#12 0x5631d654bf7e <unknown>\n#13 0x5631d68018d8 <unknown>\n#14 0x5631d6805800 <unknown>\n#15 0x5631d680fcfc <unknown>\n#16 0x5631d6806418 <unknown>\n#17 0x5631d67d342f <unknown>\n#18 0x5631d682a4e8 <unknown>\n#19 0x5631d682a6b4 <unknown>\n#20 0x5631d683b143 <unknown>\n#21 0x7f0277494ac3 <unknown>","statusTrace":"self = <test_main_page.TestMainPage.TestHotSellerSection object at 0x7fdb4c097150>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4dade8cd2830e80af713643fe13e8730\")>\n\n    @pytest.mark.xfail(reason=\"In CI the test failed in PR#203\")\n    def test_check_card_price(self, driver):\n        \"\"\"This test checks that the card has a price and a price in USD\"\"\"\n        page = MainPage(driver, MAIN_PAGE_URL)\n        page.open()\n>       text = page.check_card_price()\n\ntests/test_main_page.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:49: in check_card_price\n    text = self.get_text(self.locators.CARD_PRICE)\npages/base_page.py:145: in get_text\n    return text.text\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:89: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:394: in _execute\n    return self._parent.execute(command, params)\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fdb4bd107d0>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#19 0x5631d682a6b4 \\\\u003Cunknown>\\\\n#20 0x5631d683b143 \\\\u003Cunknown>\\\\n#21 0x7f0277494ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\nE         (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0x5631d683bfb3 <unknown>\nE       #1 0x5631d650f4a7 <unknown>\nE       #2 0x5631d6514509 <unknown>\nE       #3 0x5631d6516120 <unknown>\nE       #4 0x5631d65161dc <unknown>\nE       #5 0x5631d6551782 <unknown>\nE       #6 0x5631d6578942 <unknown>\nE       #7 0x5631d654c776 <unknown>\nE       #8 0x5631d6578b0e <unknown>\nE       #9 0x5631d6591c02 <unknown>\nE       #10 0x5631d6578713 <unknown>\nE       #11 0x5631d654b18b <unknown>\nE       #12 0x5631d654bf7e <unknown>\nE       #13 0x5631d68018d8 <unknown>\nE       #14 0x5631d6805800 <unknown>\nE       #15 0x5631d680fcfc <unknown>\nE       #16 0x5631d6806418 <unknown>\nE       #17 0x5631d67d342f <unknown>\nE       #18 0x5631d682a4e8 <unknown>\nE       #19 0x5631d682a6b4 <unknown>\nE       #20 0x5631d683b143 <unknown>\nE       #21 0x7f0277494ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1699668702733,"stop":1699668702820,"duration":87},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"clear_allure_result_folder","time":{"start":1699668702820,"stop":1699668702820,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"driver","time":{"start":1699669505077,"stop":1699669506231,"duration":1154},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"description":"This test checks that the card has a price and a price in USD","status":"skipped","statusMessage":"XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x5631d683bfb3 <unknown>\n#1 0x5631d650f4a7 <unknown>\n#2 0x5631d6514509 <unknown>\n#3 0x5631d6516120 <unknown>\n#4 0x5631d65161dc <unknown>\n#5 0x5631d6551782 <unknown>\n#6 0x5631d6578942 <unknown>\n#7 0x5631d654c776 <unknown>\n#8 0x5631d6578b0e <unknown>\n#9 0x5631d6591c02 <unknown>\n#10 0x5631d6578713 <unknown>\n#11 0x5631d654b18b <unknown>\n#12 0x5631d654bf7e <unknown>\n#13 0x5631d68018d8 <unknown>\n#14 0x5631d6805800 <unknown>\n#15 0x5631d680fcfc <unknown>\n#16 0x5631d6806418 <unknown>\n#17 0x5631d67d342f <unknown>\n#18 0x5631d682a4e8 <unknown>\n#19 0x5631d682a6b4 <unknown>\n#20 0x5631d683b143 <unknown>\n#21 0x7f0277494ac3 <unknown>","statusTrace":"self = <test_main_page.TestMainPage.TestHotSellerSection object at 0x7fdb4c097150>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4dade8cd2830e80af713643fe13e8730\")>\n\n    @pytest.mark.xfail(reason=\"In CI the test failed in PR#203\")\n    def test_check_card_price(self, driver):\n        \"\"\"This test checks that the card has a price and a price in USD\"\"\"\n        page = MainPage(driver, MAIN_PAGE_URL)\n        page.open()\n>       text = page.check_card_price()\n\ntests/test_main_page.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:49: in check_card_price\n    text = self.get_text(self.locators.CARD_PRICE)\npages/base_page.py:145: in get_text\n    return text.text\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:89: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:394: in _execute\n    return self._parent.execute(command, params)\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fdb4bd107d0>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#19 0x5631d682a6b4 \\\\u003Cunknown>\\\\n#20 0x5631d683b143 \\\\u003Cunknown>\\\\n#21 0x7f0277494ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\nE         (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0x5631d683bfb3 <unknown>\nE       #1 0x5631d650f4a7 <unknown>\nE       #2 0x5631d6514509 <unknown>\nE       #3 0x5631d6516120 <unknown>\nE       #4 0x5631d65161dc <unknown>\nE       #5 0x5631d6551782 <unknown>\nE       #6 0x5631d6578942 <unknown>\nE       #7 0x5631d654c776 <unknown>\nE       #8 0x5631d6578b0e <unknown>\nE       #9 0x5631d6591c02 <unknown>\nE       #10 0x5631d6578713 <unknown>\nE       #11 0x5631d654b18b <unknown>\nE       #12 0x5631d654bf7e <unknown>\nE       #13 0x5631d68018d8 <unknown>\nE       #14 0x5631d6805800 <unknown>\nE       #15 0x5631d680fcfc <unknown>\nE       #16 0x5631d6806418 <unknown>\nE       #17 0x5631d67d342f <unknown>\nE       #18 0x5631d682a4e8 <unknown>\nE       #19 0x5631d682a6b4 <unknown>\nE       #20 0x5631d683b143 <unknown>\nE       #21 0x7f0277494ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException","steps":[{"name":"Open a browser","time":{"start":1699669506232,"stop":1699669507394,"duration":1162},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Get element text","time":{"start":1699669507394,"stop":1699669507597,"duration":203},"status":"broken","statusMessage":"selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x5631d683bfb3 <unknown>\n#1 0x5631d650f4a7 <unknown>\n#2 0x5631d6514509 <unknown>\n#3 0x5631d6516120 <unknown>\n#4 0x5631d65161dc <unknown>\n#5 0x5631d6551782 <unknown>\n#6 0x5631d6578942 <unknown>\n#7 0x5631d654c776 <unknown>\n#8 0x5631d6578b0e <unknown>\n#9 0x5631d6591c02 <unknown>\n#10 0x5631d6578713 <unknown>\n#11 0x5631d654b18b <unknown>\n#12 0x5631d654bf7e <unknown>\n#13 0x5631d68018d8 <unknown>\n#14 0x5631d6805800 <unknown>\n#15 0x5631d680fcfc <unknown>\n#16 0x5631d6806418 <unknown>\n#17 0x5631d67d342f <unknown>\n#18 0x5631d682a4e8 <unknown>\n#19 0x5631d682a6b4 <unknown>\n#20 0x5631d683b143 <unknown>\n#21 0x7f0277494ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 145, in get_text\n    return text.text\n           ^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py\", line 89, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py\", line 394, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Find a visible element","time":{"start":1699669507394,"stop":1699669507511,"duration":117},"status":"passed","steps":[{"name":"Find a present element","time":{"start":1699669507394,"stop":1699669507427,"duration":33},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', \"li[class='product-item']:nth-child(4) span[class='price']\")"},{"name":"timeout","value":"5"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true},{"name":"Go to specified element","time":{"start":1699669507427,"stop":1699669507449,"duration":22},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"element","value":"<selenium.webdriver.remote.webelement.WebElement (session=\"4dade8cd2830e80af713643fe13e8730\", element=\"38C50DD783A21849A181DD4D2AF10CD3_element_10\")>"}],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', \"li[class='product-item']:nth-child(4) span[class='price']\")"},{"name":"timeout","value":"10"}],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[{"name":"locator","value":"('css selector', \"li[class='product-item']:nth-child(4) span[class='price']\")"}],"shouldDisplayMessage":true,"stepsCount":3,"attachmentsCount":0,"hasContent":true}],"attachments":[{"uid":"6481aef401911f03","name":"Screenshot","source":"6481aef401911f03.png","type":"image/png","size":135319},{"uid":"cd1ab01a53f0b926","name":"HTML source","source":"cd1ab01a53f0b926.html","type":"text/html","size":109315}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":2,"hasContent":true},"afterStages":[{"name":"driver::0","time":{"start":1699669507980,"stop":1699669508045,"duration":65},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"clear_allure_result_folder::0","time":{"start":1699670425583,"stop":1699670425583,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"epic","value":"Main Page"},{"name":"feature","value":"Testing Hot Seller Section"},{"name":"tag","value":"@pytest.mark.xfail(reason='In CI the test failed in PR#203')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_main_page"},{"name":"subSuite","value":"TestMainPage"},{"name":"host","value":"fv-az313-467"},{"name":"thread","value":"2963-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_main_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":2,"passed":4,"unknown":0,"total":6},"items":[{"uid":"6105a47f1a551ac","reportUrl":"https://verafes.github.io/luma_project/124//#testresult/6105a47f1a551ac","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1699579372767,"stop":1699579374086,"duration":1319}},{"uid":"b7105509b3bab143","reportUrl":"https://verafes.github.io/luma_project/123//#testresult/b7105509b3bab143","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1699492919779,"stop":1699492921025,"duration":1246}},{"uid":"f6f93a0e242fb70d","reportUrl":"https://verafes.github.io/luma_project/122//#testresult/f6f93a0e242fb70d","status":"skipped","statusDetails":"XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x557e945edfb3 <unknown>\n#1 0x557e942c14a7 <unknown>\n#2 0x557e942c6509 <unknown>\n#3 0x557e942c840a <unknown>\n#4 0x557e943446ef <unknown>\n#5 0x557e9432a942 <unknown>\n#6 0x557e94343c02 <unknown>\n#7 0x557e9432a713 <unknown>\n#8 0x557e942fd18b <unknown>\n#9 0x557e942fdf7e <unknown>\n#10 0x557e945b38d8 <unknown>\n#11 0x557e945b7800 <unknown>\n#12 0x557e945c1cfc <unknown>\n#13 0x557e945b8418 <unknown>\n#14 0x557e9458542f <unknown>\n#15 0x557e945dc4e8 <unknown>\n#16 0x557e945dc6b4 <unknown>\n#17 0x557e945ed143 <unknown>\n#18 0x7f263e294ac3 <unknown>","time":{"start":1699406565886,"stop":1699406566938,"duration":1052}},{"uid":"f6ea96a14f39e276","reportUrl":"https://verafes.github.io/luma_project/121//#testresult/f6ea96a14f39e276","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1699320160382,"stop":1699320161604,"duration":1222}},{"uid":"fc016adda7c7988b","reportUrl":"https://verafes.github.io/luma_project/120//#testresult/fc016adda7c7988b","status":"passed","statusDetails":"XPASS In CI the test failed in PR#203","time":{"start":1699233741215,"stop":1699233744124,"duration":2909}}]},"tags":["@pytest.mark.xfail(reason='In CI the test failed in PR#203')"]},"source":"b13b95366244d1ad.json","parameterValues":[]}