{"uid":"20c71a1d9ea6476e","name":"test 04.02.07 create an account with incorrect confirm password","fullName":"tests.test_create_an_account.TestCreateAnAccount#test_tc_04_02_07_create_account_with_incorrect_confirm_password","historyId":"09679f850e6cf760d69d28578925e32f","time":{"start":1735438078197,"stop":1735438083340,"duration":5143},"description":" Verify that customer can't Create An Account with incorrect confirm password","descriptionHtml":"<p>Verify that customer can't Create An Account with incorrect confirm password</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5652c324a31a <unknown>\n#1 0x5652c2d606e0 <unknown>\n#2 0x5652c2daf3e6 <unknown>\n#3 0x5652c2daf681 <unknown>\n#4 0x5652c2df4b04 <unknown>\n#5 0x5652c2dd348d <unknown>\n#6 0x5652c2df1ed7 <unknown>\n#7 0x5652c2dd3203 <unknown>\n#8 0x5652c2da1cc0 <unknown>\n#9 0x5652c2da2c9e <unknown>\n#10 0x5652c3217d0b <unknown>\n#11 0x5652c321bc92 <unknown>\n#12 0x5652c3204b3c <unknown>\n#13 0x5652c321c807 <unknown>\n#14 0x5652c31ea0df <unknown>\n#15 0x5652c3239578 <unknown>\n#16 0x5652c3239740 <unknown>\n#17 0x5652c3249196 <unknown>\n#18 0x7f4a26e9ca94 <unknown>\n#19 0x7f4a26f29c3c <unknown>","statusTrace":"self = <test_create_an_account.TestCreateAnAccount object at 0x7fb437520f50>\ncreate_account_page = <pages.create_an_account_page.CreateAccountPage object at 0x7fb4380c2d50>\n\n    @allure.title('test 04.02.07 create an account with incorrect confirm password')\n    def test_tc_04_02_07_create_account_with_incorrect_confirm_password(self, create_account_page):\n        \"\"\" Verify that customer can't Create An Account with incorrect confirm password\"\"\"\n>       message = create_account_page.create_with_incorrect_confirm_password()\n\ntests/test_create_an_account.py:208: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/create_an_account_page.py:365: in create_with_incorrect_confirm_password\n    self.element_is_visible(self.locators.FIRST_NAME).send_keys('test727')\npages/base_page.py:29: in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\npages/base_page.py:50: in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f1c9608d50b2bfccdfdf3075f36a6577\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x7fb4365298a0>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x5652c324a31a <unknown>\nE       #1 0x5652c2d606e0 <unknown>\nE       #2 0x5652c2daf3e6 <unknown>\nE       #3 0x5652c2daf681 <unknown>\nE       #4 0x5652c2df4b04 <unknown>\nE       #5 0x5652c2dd348d <unknown>\nE       #6 0x5652c2df1ed7 <unknown>\nE       #7 0x5652c2dd3203 <unknown>\nE       #8 0x5652c2da1cc0 <unknown>\nE       #9 0x5652c2da2c9e <unknown>\nE       #10 0x5652c3217d0b <unknown>\nE       #11 0x5652c321bc92 <unknown>\nE       #12 0x5652c3204b3c <unknown>\nE       #13 0x5652c321c807 <unknown>\nE       #14 0x5652c31ea0df <unknown>\nE       #15 0x5652c3239578 <unknown>\nE       #16 0x5652c3239740 <unknown>\nE       #17 0x5652c3249196 <unknown>\nE       #18 0x7f4a26e9ca94 <unknown>\nE       #19 0x7f4a26f29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1735436722698,"stop":1735436722759,"duration":61},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder","time":{"start":1735436722760,"stop":1735436722760,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1735438076797,"stop":1735438078059,"duration":1262},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"create_account_page","time":{"start":1735438078059,"stop":1735438078196,"duration":137},"status":"passed","steps":[{"name":"Open a browser","time":{"start":1735438078059,"stop":1735438078196,"duration":137},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"description":" Verify that customer can't Create An Account with incorrect confirm password","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5652c324a31a <unknown>\n#1 0x5652c2d606e0 <unknown>\n#2 0x5652c2daf3e6 <unknown>\n#3 0x5652c2daf681 <unknown>\n#4 0x5652c2df4b04 <unknown>\n#5 0x5652c2dd348d <unknown>\n#6 0x5652c2df1ed7 <unknown>\n#7 0x5652c2dd3203 <unknown>\n#8 0x5652c2da1cc0 <unknown>\n#9 0x5652c2da2c9e <unknown>\n#10 0x5652c3217d0b <unknown>\n#11 0x5652c321bc92 <unknown>\n#12 0x5652c3204b3c <unknown>\n#13 0x5652c321c807 <unknown>\n#14 0x5652c31ea0df <unknown>\n#15 0x5652c3239578 <unknown>\n#16 0x5652c3239740 <unknown>\n#17 0x5652c3249196 <unknown>\n#18 0x7f4a26e9ca94 <unknown>\n#19 0x7f4a26f29c3c <unknown>","statusTrace":"self = <test_create_an_account.TestCreateAnAccount object at 0x7fb437520f50>\ncreate_account_page = <pages.create_an_account_page.CreateAccountPage object at 0x7fb4380c2d50>\n\n    @allure.title('test 04.02.07 create an account with incorrect confirm password')\n    def test_tc_04_02_07_create_account_with_incorrect_confirm_password(self, create_account_page):\n        \"\"\" Verify that customer can't Create An Account with incorrect confirm password\"\"\"\n>       message = create_account_page.create_with_incorrect_confirm_password()\n\ntests/test_create_an_account.py:208: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/create_an_account_page.py:365: in create_with_incorrect_confirm_password\n    self.element_is_visible(self.locators.FIRST_NAME).send_keys('test727')\npages/base_page.py:29: in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\npages/base_page.py:50: in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f1c9608d50b2bfccdfdf3075f36a6577\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x7fb4365298a0>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x5652c324a31a <unknown>\nE       #1 0x5652c2d606e0 <unknown>\nE       #2 0x5652c2daf3e6 <unknown>\nE       #3 0x5652c2daf681 <unknown>\nE       #4 0x5652c2df4b04 <unknown>\nE       #5 0x5652c2dd348d <unknown>\nE       #6 0x5652c2df1ed7 <unknown>\nE       #7 0x5652c2dd3203 <unknown>\nE       #8 0x5652c2da1cc0 <unknown>\nE       #9 0x5652c2da2c9e <unknown>\nE       #10 0x5652c3217d0b <unknown>\nE       #11 0x5652c321bc92 <unknown>\nE       #12 0x5652c3204b3c <unknown>\nE       #13 0x5652c321c807 <unknown>\nE       #14 0x5652c31ea0df <unknown>\nE       #15 0x5652c3239578 <unknown>\nE       #16 0x5652c3239740 <unknown>\nE       #17 0x5652c3249196 <unknown>\nE       #18 0x7f4a26e9ca94 <unknown>\nE       #19 0x7f4a26f29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException","steps":[{"name":"Create an account with incorrect confirm password","time":{"start":1735438078197,"stop":1735438083340,"duration":5143},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5652c324a31a <unknown>\n#1 0x5652c2d606e0 <unknown>\n#2 0x5652c2daf3e6 <unknown>\n#3 0x5652c2daf681 <unknown>\n#4 0x5652c2df4b04 <unknown>\n#5 0x5652c2dd348d <unknown>\n#6 0x5652c2df1ed7 <unknown>\n#7 0x5652c2dd3203 <unknown>\n#8 0x5652c2da1cc0 <unknown>\n#9 0x5652c2da2c9e <unknown>\n#10 0x5652c3217d0b <unknown>\n#11 0x5652c321bc92 <unknown>\n#12 0x5652c3204b3c <unknown>\n#13 0x5652c321c807 <unknown>\n#14 0x5652c31ea0df <unknown>\n#15 0x5652c3239578 <unknown>\n#16 0x5652c3239740 <unknown>\n#17 0x5652c3249196 <unknown>\n#18 0x7f4a26e9ca94 <unknown>\n#19 0x7f4a26f29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/create_an_account_page.py\", line 365, in create_with_incorrect_confirm_password\n    self.element_is_visible(self.locators.FIRST_NAME).send_keys('test727')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 29, in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 50, in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Find a visible element","time":{"start":1735438078197,"stop":1735438083339,"duration":5142},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5652c324a31a <unknown>\n#1 0x5652c2d606e0 <unknown>\n#2 0x5652c2daf3e6 <unknown>\n#3 0x5652c2daf681 <unknown>\n#4 0x5652c2df4b04 <unknown>\n#5 0x5652c2dd348d <unknown>\n#6 0x5652c2df1ed7 <unknown>\n#7 0x5652c2dd3203 <unknown>\n#8 0x5652c2da1cc0 <unknown>\n#9 0x5652c2da2c9e <unknown>\n#10 0x5652c3217d0b <unknown>\n#11 0x5652c321bc92 <unknown>\n#12 0x5652c3204b3c <unknown>\n#13 0x5652c321c807 <unknown>\n#14 0x5652c31ea0df <unknown>\n#15 0x5652c3239578 <unknown>\n#16 0x5652c3239740 <unknown>\n#17 0x5652c3249196 <unknown>\n#18 0x7f4a26e9ca94 <unknown>\n#19 0x7f4a26f29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 29, in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 50, in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Find a present element","time":{"start":1735438078197,"stop":1735438083339,"duration":5142},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5652c324a31a <unknown>\n#1 0x5652c2d606e0 <unknown>\n#2 0x5652c2daf3e6 <unknown>\n#3 0x5652c2daf681 <unknown>\n#4 0x5652c2df4b04 <unknown>\n#5 0x5652c2dd348d <unknown>\n#6 0x5652c2df1ed7 <unknown>\n#7 0x5652c2dd3203 <unknown>\n#8 0x5652c2da1cc0 <unknown>\n#9 0x5652c2da2c9e <unknown>\n#10 0x5652c3217d0b <unknown>\n#11 0x5652c321bc92 <unknown>\n#12 0x5652c3204b3c <unknown>\n#13 0x5652c321c807 <unknown>\n#14 0x5652c31ea0df <unknown>\n#15 0x5652c3239578 <unknown>\n#16 0x5652c3239740 <unknown>\n#17 0x5652c3249196 <unknown>\n#18 0x7f4a26e9ca94 <unknown>\n#19 0x7f4a26f29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 50, in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[{"name":"locator","value":"('id', 'firstname')"},{"name":"timeout","value":"5"}],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[{"name":"locator","value":"('id', 'firstname')"},{"name":"timeout","value":"10"}],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"e23eb349c34b8dd8","name":"Screenshot","source":"e23eb349c34b8dd8.png","type":"image/png","size":87708},{"uid":"efc1c573424a26a","name":"HTML source","source":"efc1c573424a26a.html","type":"text/html","size":6660}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":3,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1735438083446,"stop":1735438083511,"duration":65},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_allure_result_folder::0","time":{"start":1735439455168,"stop":1735439455168,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Create An Account"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_create_an_account"},{"name":"subSuite","value":"TestCreateAnAccount"},{"name":"host","value":"fv-az1314-353"},{"name":"thread","value":"2780-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_create_an_account"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"20c71a1d9ea6476e.json","parameterValues":[]}