{
  "uid" : "858bca3000fe09ae",
  "name" : "test_check_card_price",
  "fullName" : "tests.test_main_page.TestHotSellerSection#test_check_card_price",
  "historyId" : "f4026d9f96acc9996f781ecba7818e56",
  "time" : {
    "start" : 1710638106847,
    "stop" : 1710638107712,
    "duration" : 865
  },
  "description" : "This test checks that the card has a price and a price in USD",
  "descriptionHtml" : "<p>This test checks that the card has a price and a price in USD</p>\n",
  "status" : "skipped",
  "statusMessage" : "XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=122.0.6261.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x60a405ef4ec3 <unknown>\n#1 0x60a405becce6 <unknown>\n#2 0x60a405bf20bc <unknown>\n#3 0x60a405bf3e4b <unknown>\n#4 0x60a405bf3eec <unknown>\n#5 0x60a405c32322 <unknown>\n#6 0x60a405c59eb2 <unknown>\n#7 0x60a405c2c6b8 <unknown>\n#8 0x60a405c5a07e <unknown>\n#9 0x60a405c78899 <unknown>\n#10 0x60a405c59c53 <unknown>\n#11 0x60a405c2adb3 <unknown>\n#12 0x60a405c2b77e <unknown>\n#13 0x60a405eba7fb <unknown>\n#14 0x60a405ebe815 <unknown>\n#15 0x60a405ea8111 <unknown>\n#16 0x60a405ebf3a2 <unknown>\n#17 0x60a405e8c1ef <unknown>\n#18 0x60a405ee34b8 <unknown>\n#19 0x60a405ee36b3 <unknown>\n#20 0x60a405ef4074 <unknown>\n#21 0x789ec9e94ac3 <unknown>",
  "statusTrace" : "self = <test_main_page.TestMainPage.TestHotSellerSection object at 0x73a9e3223150>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"fde7cef03c13014c7ba8c2819f993927\")>\n\n    @pytest.mark.xfail(reason=\"In CI the test failed in PR#203\")\n    def test_check_card_price(self, driver):\n        \"\"\"This test checks that the card has a price and a price in USD\"\"\"\n        page = MainPage(driver, MAIN_PAGE_URL)\n        page.open()\n>       text = page.check_card_price()\n\ntests/test_main_page.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:49: in check_card_price\n    text = self.get_text(self.locators.CARD_PRICE)\npages/base_page.py:145: in get_text\n    return text.text\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:89: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:394: in _execute\n    return self._parent.execute(command, params)\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x73a9e35e9150>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#19 0x60a405ee36b3 \\\\u003Cunknown>\\\\n#20 0x60a405ef4074 \\\\u003Cunknown>\\\\n#21 0x789ec9e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\nE         (Session info: chrome=122.0.6261.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0x60a405ef4ec3 <unknown>\nE       #1 0x60a405becce6 <unknown>\nE       #2 0x60a405bf20bc <unknown>\nE       #3 0x60a405bf3e4b <unknown>\nE       #4 0x60a405bf3eec <unknown>\nE       #5 0x60a405c32322 <unknown>\nE       #6 0x60a405c59eb2 <unknown>\nE       #7 0x60a405c2c6b8 <unknown>\nE       #8 0x60a405c5a07e <unknown>\nE       #9 0x60a405c78899 <unknown>\nE       #10 0x60a405c59c53 <unknown>\nE       #11 0x60a405c2adb3 <unknown>\nE       #12 0x60a405c2b77e <unknown>\nE       #13 0x60a405eba7fb <unknown>\nE       #14 0x60a405ebe815 <unknown>\nE       #15 0x60a405ea8111 <unknown>\nE       #16 0x60a405ebf3a2 <unknown>\nE       #17 0x60a405e8c1ef <unknown>\nE       #18 0x60a405ee34b8 <unknown>\nE       #19 0x60a405ee36b3 <unknown>\nE       #20 0x60a405ef4074 <unknown>\nE       #21 0x789ec9e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1710637714205,
      "stop" : 1710637714267,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1710638105817,
      "stop" : 1710638106846,
      "duration" : 1029
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_result_folder",
    "time" : {
      "start" : 1710637714267,
      "stop" : 1710637714267,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "This test checks that the card has a price and a price in USD",
    "status" : "skipped",
    "statusMessage" : "XFAIL In CI the test failed in PR#203\n\nselenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=122.0.6261.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x60a405ef4ec3 <unknown>\n#1 0x60a405becce6 <unknown>\n#2 0x60a405bf20bc <unknown>\n#3 0x60a405bf3e4b <unknown>\n#4 0x60a405bf3eec <unknown>\n#5 0x60a405c32322 <unknown>\n#6 0x60a405c59eb2 <unknown>\n#7 0x60a405c2c6b8 <unknown>\n#8 0x60a405c5a07e <unknown>\n#9 0x60a405c78899 <unknown>\n#10 0x60a405c59c53 <unknown>\n#11 0x60a405c2adb3 <unknown>\n#12 0x60a405c2b77e <unknown>\n#13 0x60a405eba7fb <unknown>\n#14 0x60a405ebe815 <unknown>\n#15 0x60a405ea8111 <unknown>\n#16 0x60a405ebf3a2 <unknown>\n#17 0x60a405e8c1ef <unknown>\n#18 0x60a405ee34b8 <unknown>\n#19 0x60a405ee36b3 <unknown>\n#20 0x60a405ef4074 <unknown>\n#21 0x789ec9e94ac3 <unknown>",
    "statusTrace" : "self = <test_main_page.TestMainPage.TestHotSellerSection object at 0x73a9e3223150>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"fde7cef03c13014c7ba8c2819f993927\")>\n\n    @pytest.mark.xfail(reason=\"In CI the test failed in PR#203\")\n    def test_check_card_price(self, driver):\n        \"\"\"This test checks that the card has a price and a price in USD\"\"\"\n        page = MainPage(driver, MAIN_PAGE_URL)\n        page.open()\n>       text = page.check_card_price()\n\ntests/test_main_page.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:49: in check_card_price\n    text = self.get_text(self.locators.CARD_PRICE)\npages/base_page.py:145: in get_text\n    return text.text\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:89: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py:394: in _execute\n    return self._parent.execute(command, params)\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x73a9e35e9150>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...\\\\n#19 0x60a405ee36b3 \\\\u003Cunknown>\\\\n#20 0x60a405ef4074 \\\\u003Cunknown>\\\\n#21 0x789ec9e94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\nE         (Session info: chrome=122.0.6261.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       #0 0x60a405ef4ec3 <unknown>\nE       #1 0x60a405becce6 <unknown>\nE       #2 0x60a405bf20bc <unknown>\nE       #3 0x60a405bf3e4b <unknown>\nE       #4 0x60a405bf3eec <unknown>\nE       #5 0x60a405c32322 <unknown>\nE       #6 0x60a405c59eb2 <unknown>\nE       #7 0x60a405c2c6b8 <unknown>\nE       #8 0x60a405c5a07e <unknown>\nE       #9 0x60a405c78899 <unknown>\nE       #10 0x60a405c59c53 <unknown>\nE       #11 0x60a405c2adb3 <unknown>\nE       #12 0x60a405c2b77e <unknown>\nE       #13 0x60a405eba7fb <unknown>\nE       #14 0x60a405ebe815 <unknown>\nE       #15 0x60a405ea8111 <unknown>\nE       #16 0x60a405ebf3a2 <unknown>\nE       #17 0x60a405e8c1ef <unknown>\nE       #18 0x60a405ee34b8 <unknown>\nE       #19 0x60a405ee36b3 <unknown>\nE       #20 0x60a405ef4074 <unknown>\nE       #21 0x789ec9e94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: StaleElementReferenceException",
    "steps" : [ {
      "name" : "Open a browser",
      "time" : {
        "start" : 1710638106847,
        "stop" : 1710638107609,
        "duration" : 762
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Get element text",
      "time" : {
        "start" : 1710638107609,
        "stop" : 1710638107711,
        "duration" : 102
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: chrome=122.0.6261.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n#0 0x60a405ef4ec3 <unknown>\n#1 0x60a405becce6 <unknown>\n#2 0x60a405bf20bc <unknown>\n#3 0x60a405bf3e4b <unknown>\n#4 0x60a405bf3eec <unknown>\n#5 0x60a405c32322 <unknown>\n#6 0x60a405c59eb2 <unknown>\n#7 0x60a405c2c6b8 <unknown>\n#8 0x60a405c5a07e <unknown>\n#9 0x60a405c78899 <unknown>\n#10 0x60a405c59c53 <unknown>\n#11 0x60a405c2adb3 <unknown>\n#12 0x60a405c2b77e <unknown>\n#13 0x60a405eba7fb <unknown>\n#14 0x60a405ebe815 <unknown>\n#15 0x60a405ea8111 <unknown>\n#16 0x60a405ebf3a2 <unknown>\n#17 0x60a405e8c1ef <unknown>\n#18 0x60a405ee34b8 <unknown>\n#19 0x60a405ee36b3 <unknown>\n#20 0x60a405ef4074 <unknown>\n#21 0x789ec9e94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 145, in get_text\n    return text.text\n           ^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py\", line 89, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py\", line 394, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ {
        "name" : "Find a visible element",
        "time" : {
          "start" : 1710638107609,
          "stop" : 1710638107673,
          "duration" : 64
        },
        "status" : "passed",
        "steps" : [ {
          "name" : "Find a present element",
          "time" : {
            "start" : 1710638107609,
            "stop" : 1710638107634,
            "duration" : 25
          },
          "status" : "passed",
          "steps" : [ ],
          "attachments" : [ ],
          "parameters" : [ {
            "name" : "locator",
            "value" : "('css selector', \"li[class='product-item']:nth-child(3) span[class='price']\")"
          }, {
            "name" : "timeout",
            "value" : "5"
          } ],
          "stepsCount" : 0,
          "attachmentsCount" : 0,
          "shouldDisplayMessage" : false,
          "hasContent" : true
        }, {
          "name" : "Go to specified element",
          "time" : {
            "start" : 1710638107634,
            "stop" : 1710638107640,
            "duration" : 6
          },
          "status" : "passed",
          "steps" : [ ],
          "attachments" : [ ],
          "parameters" : [ {
            "name" : "element",
            "value" : "<selenium.webdriver.remote.webelement.WebElement (session=\"fde7cef03c13014c7ba8c2819f993927\", element=\"f.DE9E4CB0E9CCA9DD09063872F35E86E4.d.6CB78AC4701C4E5730F3C8BA0952158E.e.15\")>"
          } ],
          "stepsCount" : 0,
          "attachmentsCount" : 0,
          "shouldDisplayMessage" : false,
          "hasContent" : true
        } ],
        "attachments" : [ ],
        "parameters" : [ {
          "name" : "locator",
          "value" : "('css selector', \"li[class='product-item']:nth-child(3) span[class='price']\")"
        }, {
          "name" : "timeout",
          "value" : "10"
        } ],
        "stepsCount" : 2,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "locator",
        "value" : "('css selector', \"li[class='product-item']:nth-child(3) span[class='price']\")"
      } ],
      "stepsCount" : 3,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "7c94fc5e17dd8b4e",
      "name" : "Screenshot",
      "source" : "7c94fc5e17dd8b4e.png",
      "type" : "image/png",
      "size" : 131690
    }, {
      "uid" : "764617334f2d0389",
      "name" : "HTML source",
      "source" : "764617334f2d0389.html",
      "type" : "text/html",
      "size" : 110806
    } ],
    "parameters" : [ ],
    "stepsCount" : 5,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1710638107977,
      "stop" : 1710638108044,
      "duration" : 67
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_result_folder::0",
    "time" : {
      "start" : 1710638770108,
      "stop" : 1710638770108,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Testing Hot Seller Section"
  }, {
    "name" : "epic",
    "value" : "Main Page"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='In CI the test failed in PR#203')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_main_page"
  }, {
    "name" : "subSuite",
    "value" : "TestMainPage"
  }, {
    "name" : "host",
    "value" : "fv-az1490-915"
  }, {
    "name" : "thread",
    "value" : "3042-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_main_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(reason='In CI the test failed in PR#203')" ]
  },
  "source" : "858bca3000fe09ae.json",
  "parameterValues" : [ ]
}