{
  "uid" : "a010ea56a6599f81",
  "name" : "TC 03.02.01 to 03_02_10 Verify Failed Login, no error validation",
  "fullName" : "tests.test_sign_in.TestFailedLogin#test_03_02_01_to_03_02_10_login",
  "historyId" : "0029e97b34628286aac0dce42d8b2f6a",
  "time" : {
    "start" : 1737856973034,
    "stop" : 1737856978403,
    "duration" : 5369
  },
  "description" : "Check Success and Failed Login, no error validation",
  "descriptionHtml" : "<p>Check Success and Failed Login, no error validation</p>\n",
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x56319bad47ca <unknown>\n#1 0x56319b5cc2f0 <unknown>\n#2 0x56319b61c035 <unknown>\n#3 0x56319b61c251 <unknown>\n#4 0x56319b662054 <unknown>\n#5 0x56319b6409dd <unknown>\n#6 0x56319b65f3b3 <unknown>\n#7 0x56319b640753 <unknown>\n#8 0x56319b60dbaa <unknown>\n#9 0x56319b60edfe <unknown>\n#10 0x56319ba9f38b <unknown>\n#11 0x56319baa3307 <unknown>\n#12 0x56319ba8be7c <unknown>\n#13 0x56319baa3ec7 <unknown>\n#14 0x56319ba7024f <unknown>\n#15 0x56319bac32f8 <unknown>\n#16 0x56319bac34c0 <unknown>\n#17 0x56319bad3646 <unknown>\n#18 0x7fc5c829ca94 <unknown>\n#19 0x7fc5c8329c3c <unknown>",
  "statusTrace" : "self = <test_sign_in.TestFailedLogin object at 0x7fc2e8328590>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ec6eb9bbde1f2954281861a124e3cee8\")>\nemail = '', password = 'Test#12p@ssword'\n\n    @allure.title('TC 03.02.01 to 03_02_10 Verify Failed Login, no error validation')\n    @pytest.mark.parametrize('email, password', LOGIN)\n    def test_03_02_01_to_03_02_10_login(self, driver, email, password):\n        \"\"\"Check Success and Failed Login, no error validation\"\"\"\n        sign_in_page = SignInPage(driver, SIGN_IN_URL)\n        sign_in_page.open()\n>       sign_in_page.fill_in_email_field(email)\n\ntests/test_sign_in.py:256: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/sign_in_page.py:54: in fill_in_email_field\n    self.fill_in_field(self.check_customer_email_field_is_clickable(), email)\npages/sign_in_page.py:41: in check_customer_email_field_is_clickable\n    return self.element_is_clickable(self.locators.CUSTOMER_EMAIL)\npages/base_page.py:80: in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"ec6eb9bbde1f2954281861a124e3cee8\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7fc2e77227a0>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x56319bad47ca <unknown>\nE       #1 0x56319b5cc2f0 <unknown>\nE       #2 0x56319b61c035 <unknown>\nE       #3 0x56319b61c251 <unknown>\nE       #4 0x56319b662054 <unknown>\nE       #5 0x56319b6409dd <unknown>\nE       #6 0x56319b65f3b3 <unknown>\nE       #7 0x56319b640753 <unknown>\nE       #8 0x56319b60dbaa <unknown>\nE       #9 0x56319b60edfe <unknown>\nE       #10 0x56319ba9f38b <unknown>\nE       #11 0x56319baa3307 <unknown>\nE       #12 0x56319ba8be7c <unknown>\nE       #13 0x56319baa3ec7 <unknown>\nE       #14 0x56319ba7024f <unknown>\nE       #15 0x56319bac32f8 <unknown>\nE       #16 0x56319bac34c0 <unknown>\nE       #17 0x56319bad3646 <unknown>\nE       #18 0x7fc5c829ca94 <unknown>\nE       #19 0x7fc5c8329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "clear_allure_result_folder",
    "time" : {
      "start" : 1737854757354,
      "stop" : 1737854757354,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1737854757290,
      "stop" : 1737854757353,
      "duration" : 63
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1737856971852,
      "stop" : 1737856973033,
      "duration" : 1181
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "Check Success and Failed Login, no error validation",
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x56319bad47ca <unknown>\n#1 0x56319b5cc2f0 <unknown>\n#2 0x56319b61c035 <unknown>\n#3 0x56319b61c251 <unknown>\n#4 0x56319b662054 <unknown>\n#5 0x56319b6409dd <unknown>\n#6 0x56319b65f3b3 <unknown>\n#7 0x56319b640753 <unknown>\n#8 0x56319b60dbaa <unknown>\n#9 0x56319b60edfe <unknown>\n#10 0x56319ba9f38b <unknown>\n#11 0x56319baa3307 <unknown>\n#12 0x56319ba8be7c <unknown>\n#13 0x56319baa3ec7 <unknown>\n#14 0x56319ba7024f <unknown>\n#15 0x56319bac32f8 <unknown>\n#16 0x56319bac34c0 <unknown>\n#17 0x56319bad3646 <unknown>\n#18 0x7fc5c829ca94 <unknown>\n#19 0x7fc5c8329c3c <unknown>",
    "statusTrace" : "self = <test_sign_in.TestFailedLogin object at 0x7fc2e8328590>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ec6eb9bbde1f2954281861a124e3cee8\")>\nemail = '', password = 'Test#12p@ssword'\n\n    @allure.title('TC 03.02.01 to 03_02_10 Verify Failed Login, no error validation')\n    @pytest.mark.parametrize('email, password', LOGIN)\n    def test_03_02_01_to_03_02_10_login(self, driver, email, password):\n        \"\"\"Check Success and Failed Login, no error validation\"\"\"\n        sign_in_page = SignInPage(driver, SIGN_IN_URL)\n        sign_in_page.open()\n>       sign_in_page.fill_in_email_field(email)\n\ntests/test_sign_in.py:256: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/sign_in_page.py:54: in fill_in_email_field\n    self.fill_in_field(self.check_customer_email_field_is_clickable(), email)\npages/sign_in_page.py:41: in check_customer_email_field_is_clickable\n    return self.element_is_clickable(self.locators.CUSTOMER_EMAIL)\npages/base_page.py:80: in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"ec6eb9bbde1f2954281861a124e3cee8\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7fc2e77227a0>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x56319bad47ca <unknown>\nE       #1 0x56319b5cc2f0 <unknown>\nE       #2 0x56319b61c035 <unknown>\nE       #3 0x56319b61c251 <unknown>\nE       #4 0x56319b662054 <unknown>\nE       #5 0x56319b6409dd <unknown>\nE       #6 0x56319b65f3b3 <unknown>\nE       #7 0x56319b640753 <unknown>\nE       #8 0x56319b60dbaa <unknown>\nE       #9 0x56319b60edfe <unknown>\nE       #10 0x56319ba9f38b <unknown>\nE       #11 0x56319baa3307 <unknown>\nE       #12 0x56319ba8be7c <unknown>\nE       #13 0x56319baa3ec7 <unknown>\nE       #14 0x56319ba7024f <unknown>\nE       #15 0x56319bac32f8 <unknown>\nE       #16 0x56319bac34c0 <unknown>\nE       #17 0x56319bad3646 <unknown>\nE       #18 0x7fc5c829ca94 <unknown>\nE       #19 0x7fc5c8329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException",
    "steps" : [ {
      "name" : "Open a browser",
      "time" : {
        "start" : 1737856973034,
        "stop" : 1737856973282,
        "duration" : 248
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Fill in Email field",
      "time" : {
        "start" : 1737856973282,
        "stop" : 1737856978403,
        "duration" : 5121
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x56319bad47ca <unknown>\n#1 0x56319b5cc2f0 <unknown>\n#2 0x56319b61c035 <unknown>\n#3 0x56319b61c251 <unknown>\n#4 0x56319b662054 <unknown>\n#5 0x56319b6409dd <unknown>\n#6 0x56319b65f3b3 <unknown>\n#7 0x56319b640753 <unknown>\n#8 0x56319b60dbaa <unknown>\n#9 0x56319b60edfe <unknown>\n#10 0x56319ba9f38b <unknown>\n#11 0x56319baa3307 <unknown>\n#12 0x56319ba8be7c <unknown>\n#13 0x56319baa3ec7 <unknown>\n#14 0x56319ba7024f <unknown>\n#15 0x56319bac32f8 <unknown>\n#16 0x56319bac34c0 <unknown>\n#17 0x56319bad3646 <unknown>\n#18 0x7fc5c829ca94 <unknown>\n#19 0x7fc5c8329c3c <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/sign_in_page.py\", line 54, in fill_in_email_field\n    self.fill_in_field(self.check_customer_email_field_is_clickable(), email)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/sign_in_page.py\", line 41, in check_customer_email_field_is_clickable\n    return self.element_is_clickable(self.locators.CUSTOMER_EMAIL)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 80, in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
      "steps" : [ {
        "name" : "Check Email field is clickable",
        "time" : {
          "start" : 1737856973282,
          "stop" : 1737856978403,
          "duration" : 5121
        },
        "status" : "broken",
        "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x56319bad47ca <unknown>\n#1 0x56319b5cc2f0 <unknown>\n#2 0x56319b61c035 <unknown>\n#3 0x56319b61c251 <unknown>\n#4 0x56319b662054 <unknown>\n#5 0x56319b6409dd <unknown>\n#6 0x56319b65f3b3 <unknown>\n#7 0x56319b640753 <unknown>\n#8 0x56319b60dbaa <unknown>\n#9 0x56319b60edfe <unknown>\n#10 0x56319ba9f38b <unknown>\n#11 0x56319baa3307 <unknown>\n#12 0x56319ba8be7c <unknown>\n#13 0x56319baa3ec7 <unknown>\n#14 0x56319ba7024f <unknown>\n#15 0x56319bac32f8 <unknown>\n#16 0x56319bac34c0 <unknown>\n#17 0x56319bad3646 <unknown>\n#18 0x7fc5c829ca94 <unknown>\n#19 0x7fc5c8329c3c <unknown>\n\n",
        "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/sign_in_page.py\", line 41, in check_customer_email_field_is_clickable\n    return self.element_is_clickable(self.locators.CUSTOMER_EMAIL)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 80, in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
        "steps" : [ {
          "name" : "Find clickable elements",
          "time" : {
            "start" : 1737856973282,
            "stop" : 1737856978402,
            "duration" : 5120
          },
          "status" : "broken",
          "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x56319bad47ca <unknown>\n#1 0x56319b5cc2f0 <unknown>\n#2 0x56319b61c035 <unknown>\n#3 0x56319b61c251 <unknown>\n#4 0x56319b662054 <unknown>\n#5 0x56319b6409dd <unknown>\n#6 0x56319b65f3b3 <unknown>\n#7 0x56319b640753 <unknown>\n#8 0x56319b60dbaa <unknown>\n#9 0x56319b60edfe <unknown>\n#10 0x56319ba9f38b <unknown>\n#11 0x56319baa3307 <unknown>\n#12 0x56319ba8be7c <unknown>\n#13 0x56319baa3ec7 <unknown>\n#14 0x56319ba7024f <unknown>\n#15 0x56319bac32f8 <unknown>\n#16 0x56319bac34c0 <unknown>\n#17 0x56319bad3646 <unknown>\n#18 0x7fc5c829ca94 <unknown>\n#19 0x7fc5c8329c3c <unknown>\n\n",
          "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 80, in element_is_clickable\n    return wait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
          "steps" : [ ],
          "attachments" : [ ],
          "parameters" : [ {
            "name" : "locator",
            "value" : "('css selector', '#email')"
          }, {
            "name" : "timeout",
            "value" : "5"
          } ],
          "stepsCount" : 0,
          "attachmentsCount" : 0,
          "shouldDisplayMessage" : true,
          "hasContent" : true
        } ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 1,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "email",
        "value" : "''"
      } ],
      "stepsCount" : 2,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "dfa1c018c20d7c2e",
      "name" : "Screenshot",
      "source" : "dfa1c018c20d7c2e.png",
      "type" : "image/png",
      "size" : 25650
    }, {
      "uid" : "45bc135f19470277",
      "name" : "HTML source",
      "source" : "45bc135f19470277.html",
      "type" : "text/html",
      "size" : 258925
    } ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "clear_allure_result_folder::0",
    "time" : {
      "start" : 1737857182853,
      "stop" : 1737857182853,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver::0",
    "time" : {
      "start" : 1737856978521,
      "stop" : 1737856978585,
      "duration" : 64
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Failed Login Functionality"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_sign_in"
  }, {
    "name" : "subSuite",
    "value" : "TestFailedLogin"
  }, {
    "name" : "host",
    "value" : "fv-az1922-652"
  }, {
    "name" : "thread",
    "value" : "2797-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_sign_in"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "email",
    "value" : "''"
  }, {
    "name" : "password",
    "value" : "'Test#12p@ssword'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "a010ea56a6599f81.json",
  "parameterValues" : [ "''", "'Test#12p@ssword'" ]
}