{
  "uid" : "e46d0489bc908dd2",
  "name" : "test 04.02.07 create an account with incorrect confirm password",
  "fullName" : "tests.test_create_an_account.TestCreateAnAccount#test_tc_04_02_07_create_account_with_incorrect_confirm_password",
  "historyId" : "09679f850e6cf760d69d28578925e32f",
  "time" : {
    "start" : 1697332446136,
    "stop" : 1697332451263,
    "duration" : 5127
  },
  "description" : " Verify that customer can't Create An Account with incorrect confirm password",
  "descriptionHtml" : "<p>Verify that customer can't Create An Account with incorrect confirm password</p>\n",
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563899f216b3 <unknown>\n#1 0x563899bf71e7 <unknown>\n#2 0x563899c3e566 <unknown>\n#3 0x563899c3e651 <unknown>\n#4 0x563899c7ba74 <unknown>\n#5 0x563899c600ed <unknown>\n#6 0x563899c79322 <unknown>\n#7 0x563899c5fe93 <unknown>\n#8 0x563899c32934 <unknown>\n#9 0x563899c3371e <unknown>\n#10 0x563899ee6cb8 <unknown>\n#11 0x563899eeabf0 <unknown>\n#12 0x563899ef519c <unknown>\n#13 0x563899eeb808 <unknown>\n#14 0x563899eb827f <unknown>\n#15 0x563899f0fe88 <unknown>\n#16 0x563899f10059 <unknown>\n#17 0x563899f20843 <unknown>\n#18 0x7f9dbbe94b43 <unknown>",
  "statusTrace" : "self = <test_create_an_account.TestCreateAnAccount object at 0x7fe0b050c4d0>\ncreate_account_page = <pages.create_an_account_page.CreateAccountPage object at 0x7fe0b103ab10>\n\n    @allure.title('test 04.02.07 create an account with incorrect confirm password')\n    def test_tc_04_02_07_create_account_with_incorrect_confirm_password(self, create_account_page):\n        \"\"\" Verify that customer can't Create An Account with incorrect confirm password\"\"\"\n>       message = create_account_page.create_with_incorrect_confirm_password()\n\ntests/test_create_an_account.py:207: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/create_an_account_page.py:365: in create_with_incorrect_confirm_password\n    self.element_is_visible(self.locators.FIRST_NAME).send_keys('test727')\npages/base_page.py:29: in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\npages/base_page.py:50: in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"e1109330a829843a8ac4b41810e1f16d\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x7fe0af3e2a20>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x563899f216b3 <unknown>\nE       #1 0x563899bf71e7 <unknown>\nE       #2 0x563899c3e566 <unknown>\nE       #3 0x563899c3e651 <unknown>\nE       #4 0x563899c7ba74 <unknown>\nE       #5 0x563899c600ed <unknown>\nE       #6 0x563899c79322 <unknown>\nE       #7 0x563899c5fe93 <unknown>\nE       #8 0x563899c32934 <unknown>\nE       #9 0x563899c3371e <unknown>\nE       #10 0x563899ee6cb8 <unknown>\nE       #11 0x563899eeabf0 <unknown>\nE       #12 0x563899ef519c <unknown>\nE       #13 0x563899eeb808 <unknown>\nE       #14 0x563899eb827f <unknown>\nE       #15 0x563899f0fe88 <unknown>\nE       #16 0x563899f10059 <unknown>\nE       #17 0x563899f20843 <unknown>\nE       #18 0x7f9dbbe94b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1697332188525,
      "stop" : 1697332188634,
      "duration" : 109
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1697332444734,
      "stop" : 1697332445889,
      "duration" : 1155
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_result_folder",
    "time" : {
      "start" : 1697332188634,
      "stop" : 1697332188634,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "create_account_page",
    "time" : {
      "start" : 1697332445889,
      "stop" : 1697332446135,
      "duration" : 246
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Open a browser",
      "time" : {
        "start" : 1697332445890,
        "stop" : 1697332446135,
        "duration" : 245
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "testStage" : {
    "description" : " Verify that customer can't Create An Account with incorrect confirm password",
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563899f216b3 <unknown>\n#1 0x563899bf71e7 <unknown>\n#2 0x563899c3e566 <unknown>\n#3 0x563899c3e651 <unknown>\n#4 0x563899c7ba74 <unknown>\n#5 0x563899c600ed <unknown>\n#6 0x563899c79322 <unknown>\n#7 0x563899c5fe93 <unknown>\n#8 0x563899c32934 <unknown>\n#9 0x563899c3371e <unknown>\n#10 0x563899ee6cb8 <unknown>\n#11 0x563899eeabf0 <unknown>\n#12 0x563899ef519c <unknown>\n#13 0x563899eeb808 <unknown>\n#14 0x563899eb827f <unknown>\n#15 0x563899f0fe88 <unknown>\n#16 0x563899f10059 <unknown>\n#17 0x563899f20843 <unknown>\n#18 0x7f9dbbe94b43 <unknown>",
    "statusTrace" : "self = <test_create_an_account.TestCreateAnAccount object at 0x7fe0b050c4d0>\ncreate_account_page = <pages.create_an_account_page.CreateAccountPage object at 0x7fe0b103ab10>\n\n    @allure.title('test 04.02.07 create an account with incorrect confirm password')\n    def test_tc_04_02_07_create_account_with_incorrect_confirm_password(self, create_account_page):\n        \"\"\" Verify that customer can't Create An Account with incorrect confirm password\"\"\"\n>       message = create_account_page.create_with_incorrect_confirm_password()\n\ntests/test_create_an_account.py:207: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/create_an_account_page.py:365: in create_with_incorrect_confirm_password\n    self.element_is_visible(self.locators.FIRST_NAME).send_keys('test727')\npages/base_page.py:29: in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\npages/base_page.py:50: in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"e1109330a829843a8ac4b41810e1f16d\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x7fe0af3e2a20>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x563899f216b3 <unknown>\nE       #1 0x563899bf71e7 <unknown>\nE       #2 0x563899c3e566 <unknown>\nE       #3 0x563899c3e651 <unknown>\nE       #4 0x563899c7ba74 <unknown>\nE       #5 0x563899c600ed <unknown>\nE       #6 0x563899c79322 <unknown>\nE       #7 0x563899c5fe93 <unknown>\nE       #8 0x563899c32934 <unknown>\nE       #9 0x563899c3371e <unknown>\nE       #10 0x563899ee6cb8 <unknown>\nE       #11 0x563899eeabf0 <unknown>\nE       #12 0x563899ef519c <unknown>\nE       #13 0x563899eeb808 <unknown>\nE       #14 0x563899eb827f <unknown>\nE       #15 0x563899f0fe88 <unknown>\nE       #16 0x563899f10059 <unknown>\nE       #17 0x563899f20843 <unknown>\nE       #18 0x7f9dbbe94b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException",
    "steps" : [ {
      "name" : "Create an account with incorrect confirm password",
      "time" : {
        "start" : 1697332446136,
        "stop" : 1697332451262,
        "duration" : 5126
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563899f216b3 <unknown>\n#1 0x563899bf71e7 <unknown>\n#2 0x563899c3e566 <unknown>\n#3 0x563899c3e651 <unknown>\n#4 0x563899c7ba74 <unknown>\n#5 0x563899c600ed <unknown>\n#6 0x563899c79322 <unknown>\n#7 0x563899c5fe93 <unknown>\n#8 0x563899c32934 <unknown>\n#9 0x563899c3371e <unknown>\n#10 0x563899ee6cb8 <unknown>\n#11 0x563899eeabf0 <unknown>\n#12 0x563899ef519c <unknown>\n#13 0x563899eeb808 <unknown>\n#14 0x563899eb827f <unknown>\n#15 0x563899f0fe88 <unknown>\n#16 0x563899f10059 <unknown>\n#17 0x563899f20843 <unknown>\n#18 0x7f9dbbe94b43 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/create_an_account_page.py\", line 365, in create_with_incorrect_confirm_password\n    self.element_is_visible(self.locators.FIRST_NAME).send_keys('test727')\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 29, in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 50, in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
      "steps" : [ {
        "name" : "Find a visible element",
        "time" : {
          "start" : 1697332446136,
          "stop" : 1697332451262,
          "duration" : 5126
        },
        "status" : "broken",
        "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563899f216b3 <unknown>\n#1 0x563899bf71e7 <unknown>\n#2 0x563899c3e566 <unknown>\n#3 0x563899c3e651 <unknown>\n#4 0x563899c7ba74 <unknown>\n#5 0x563899c600ed <unknown>\n#6 0x563899c79322 <unknown>\n#7 0x563899c5fe93 <unknown>\n#8 0x563899c32934 <unknown>\n#9 0x563899c3371e <unknown>\n#10 0x563899ee6cb8 <unknown>\n#11 0x563899eeabf0 <unknown>\n#12 0x563899ef519c <unknown>\n#13 0x563899eeb808 <unknown>\n#14 0x563899eb827f <unknown>\n#15 0x563899f0fe88 <unknown>\n#16 0x563899f10059 <unknown>\n#17 0x563899f20843 <unknown>\n#18 0x7f9dbbe94b43 <unknown>\n\n",
        "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 29, in element_is_visible\n    self.go_to_element(self.element_is_present(locator))\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 50, in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
        "steps" : [ {
          "name" : "Find a present element",
          "time" : {
            "start" : 1697332446136,
            "stop" : 1697332451262,
            "duration" : 5126
          },
          "status" : "broken",
          "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563899f216b3 <unknown>\n#1 0x563899bf71e7 <unknown>\n#2 0x563899c3e566 <unknown>\n#3 0x563899c3e651 <unknown>\n#4 0x563899c7ba74 <unknown>\n#5 0x563899c600ed <unknown>\n#6 0x563899c79322 <unknown>\n#7 0x563899c5fe93 <unknown>\n#8 0x563899c32934 <unknown>\n#9 0x563899c3371e <unknown>\n#10 0x563899ee6cb8 <unknown>\n#11 0x563899eeabf0 <unknown>\n#12 0x563899ef519c <unknown>\n#13 0x563899eeb808 <unknown>\n#14 0x563899eb827f <unknown>\n#15 0x563899f0fe88 <unknown>\n#16 0x563899f10059 <unknown>\n#17 0x563899f20843 <unknown>\n#18 0x7f9dbbe94b43 <unknown>\n\n",
          "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/luma_project/luma_project/pages/base_page.py\", line 50, in element_is_present\n    return wait(self.driver, timeout).until(EC.presence_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n",
          "steps" : [ ],
          "attachments" : [ ],
          "parameters" : [ {
            "name" : "locator",
            "value" : "('id', 'firstname')"
          }, {
            "name" : "timeout",
            "value" : "5"
          } ],
          "stepsCount" : 0,
          "attachmentsCount" : 0,
          "shouldDisplayMessage" : true,
          "hasContent" : true
        } ],
        "attachments" : [ ],
        "parameters" : [ {
          "name" : "locator",
          "value" : "('id', 'firstname')"
        }, {
          "name" : "timeout",
          "value" : "10"
        } ],
        "stepsCount" : 1,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : false,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 2,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "1e5af80b06721dda",
      "name" : "Screenshot",
      "source" : "1e5af80b06721dda.png",
      "type" : "image/png",
      "size" : 14924
    }, {
      "uid" : "31ad8b43a62a7f4c",
      "name" : "HTML source",
      "source" : "31ad8b43a62a7f4c.html",
      "type" : "text/html",
      "size" : 571
    } ],
    "parameters" : [ ],
    "stepsCount" : 3,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1697332451428,
      "stop" : 1697332451487,
      "duration" : 59
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_result_folder::0",
    "time" : {
      "start" : 1697335158583,
      "stop" : 1697335158584,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Create An Account"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_create_an_account"
  }, {
    "name" : "subSuite",
    "value" : "TestCreateAnAccount"
  }, {
    "name" : "host",
    "value" : "fv-az163-423"
  }, {
    "name" : "thread",
    "value" : "3041-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_create_an_account"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "e46d0489bc908dd2.json",
  "parameterValues" : [ ]
}